import type { DisplayLang } from "../childPortal/types";

const zhHant = {
  greeting: "嗨，{name}！",
  todayLabel: "今天的關卡",
  reviewLabel: "複習這一關",
  levelN: "第 {n} 關",
  startToday: "開始今天的練習",
  practiceAgain: "再練習一次",
  startQuiz: "開始階段檢核",
  allDoneTitle: "全部關卡都完成了！",
  allDoneBody: "可以挑一關再練習，或是去上會話課。",
  minutes: "約 {n} 分鐘",
  streak: "連續 {n} 天",
  streakAria: "連續學習 {n} 天",
  starsAria: "{n} 顆星星",
  mascotTip: "每天一點點，中文變更棒！",
  mascotAlt: "桐軒小熊嚮導",
  backToToday: "回到今天的關卡",
  pathTitle: "學習路線",
  stageN: "第 {n} 階段",
  prevStage: "上一階段",
  nextStage: "下一階段",
  stopDone: "已完成",
  stopCurrent: "進行中",
  stopLocked: "尚未解鎖",
  quizStop: "檢核",
  progressSummary: "已完成 {done} / {total} 關",
  modesTitle: "想多練一點？",
  modeCharsTitle: "認字寫字",
  modeCharsBody: "看筆順，跟著寫",
  modeDialogueTitle: "會話課",
  modeDialogueBody: "聽一聽，說一說",
  modeVocabTitle: "生詞朗讀",
  modeVocabBody: "認讀生詞與例句",
  contentsTitle: "這一關會學到",
  contentsChars: "生字",
  contentsVocab: "生詞",
  contentsIdiom: "成語故事",
  dialogueTitle: "會話課",
  dialogueBody: "選一課開始。會話課不影響關卡進度。",
  dialogueDone: "已完成",
  dialogueStart: "開始",
  dialogueLesson: "第 {n} 課",
  menuTitle: "{name} 的選單",
  menuOpen: "開啟選單",
  menuLearning: "學習設定",
  menuMore: "更多",
  menuSync: "雲端同步",
  menuSetupAgain: "重新設定學習角色",
  menuAbout: "關於桐軒",
  close: "關閉",
  feedback: "問題回報",
  support: "支持作者",
  disclaimer: "免責聲明與隱私",
};

export type HomeCopy = typeof zhHant;

const zhHans: HomeCopy = {
  greeting: "嗨，{name}！",
  todayLabel: "今天的关卡",
  reviewLabel: "复习这一关",
  levelN: "第 {n} 关",
  startToday: "开始今天的练习",
  practiceAgain: "再练习一次",
  startQuiz: "开始阶段检核",
  allDoneTitle: "全部关卡都完成了！",
  allDoneBody: "可以挑一关再练习，或是去上会话课。",
  minutes: "约 {n} 分钟",
  streak: "连续 {n} 天",
  streakAria: "连续学习 {n} 天",
  starsAria: "{n} 颗星星",
  mascotTip: "每天一点点，中文变更棒！",
  mascotAlt: "桐轩小熊向导",
  backToToday: "回到今天的关卡",
  pathTitle: "学习路线",
  stageN: "第 {n} 阶段",
  prevStage: "上一阶段",
  nextStage: "下一阶段",
  stopDone: "已完成",
  stopCurrent: "进行中",
  stopLocked: "尚未解锁",
  quizStop: "检核",
  progressSummary: "已完成 {done} / {total} 关",
  modesTitle: "想多练一点？",
  modeCharsTitle: "认字写字",
  modeCharsBody: "看笔顺，跟着写",
  modeDialogueTitle: "会话课",
  modeDialogueBody: "听一听，说一说",
  modeVocabTitle: "生词朗读",
  modeVocabBody: "认读生词与例句",
  contentsTitle: "这一关会学到",
  contentsChars: "生字",
  contentsVocab: "生词",
  contentsIdiom: "成语故事",
  dialogueTitle: "会话课",
  dialogueBody: "选一课开始。会话课不影响关卡进度。",
  dialogueDone: "已完成",
  dialogueStart: "开始",
  dialogueLesson: "第 {n} 课",
  menuTitle: "{name} 的菜单",
  menuOpen: "打开菜单",
  menuLearning: "学习设置",
  menuMore: "更多",
  menuSync: "云端同步",
  menuSetupAgain: "重新设置学习角色",
  menuAbout: "关于桐轩",
  close: "关闭",
  feedback: "问题反馈",
  support: "支持作者",
  disclaimer: "免责声明与隐私",
};

const en: HomeCopy = {
  greeting: "Hi, {name}!",
  todayLabel: "Today's level",
  reviewLabel: "Practise this level again",
  levelN: "Level {n}",
  startToday: "Start today's practice",
  practiceAgain: "Practise again",
  startQuiz: "Start the checkpoint",
  allDoneTitle: "Every level is finished!",
  allDoneBody: "Pick a level to practise again, or try a conversation lesson.",
  minutes: "About {n} min",
  streak: "{n}-day streak",
  streakAria: "{n} days in a row",
  starsAria: "{n} stars",
  mascotTip: "A little every day makes your Chinese stronger!",
  mascotAlt: "TongXuan bear guide",
  backToToday: "Back to today's level",
  pathTitle: "Learning path",
  stageN: "Stage {n}",
  prevStage: "Previous stage",
  nextStage: "Next stage",
  stopDone: "Done",
  stopCurrent: "In progress",
  stopLocked: "Locked",
  quizStop: "Check",
  progressSummary: "{done} of {total} levels done",
  modesTitle: "Want more practice?",
  modeCharsTitle: "Characters",
  modeCharsBody: "Watch the strokes, then write",
  modeDialogueTitle: "Conversation",
  modeDialogueBody: "Listen and speak",
  modeVocabTitle: "Words aloud",
  modeVocabBody: "Read words and sentences",
  contentsTitle: "In this level",
  contentsChars: "Characters",
  contentsVocab: "Words",
  contentsIdiom: "Idiom story",
  dialogueTitle: "Conversation lessons",
  dialogueBody: "Pick a lesson. These do not change your level progress.",
  dialogueDone: "Done",
  dialogueStart: "Start",
  dialogueLesson: "Lesson {n}",
  menuTitle: "{name}'s menu",
  menuOpen: "Open menu",
  menuLearning: "Learning settings",
  menuMore: "More",
  menuSync: "Cloud sync",
  menuSetupAgain: "Set up the learner again",
  menuAbout: "About TongXuan",
  close: "Close",
  feedback: "Report a problem",
  support: "Support the author",
  disclaimer: "Disclaimer and privacy",
};

const ja: HomeCopy = {
  ...en,
  greeting: "こんにちは、{name}！",
  todayLabel: "今日のレベル",
  reviewLabel: "このレベルをもう一度",
  levelN: "レベル {n}",
  startToday: "今日の練習をはじめる",
  practiceAgain: "もう一度練習する",
  startQuiz: "チェックをはじめる",
  allDoneTitle: "すべてのレベルが終わりました！",
  allDoneBody: "もう一度練習するか、会話レッスンに挑戦しましょう。",
  minutes: "約 {n} 分",
  streak: "{n} 日連続",
  streakAria: "{n} 日連続で学習",
  starsAria: "星 {n} 個",
  mascotTip: "毎日少しずつ、中国語が上手になるよ！",
  mascotAlt: "桐軒のくまガイド",
  backToToday: "今日のレベルに戻る",
  pathTitle: "学習ルート",
  stageN: "ステージ {n}",
  prevStage: "前のステージ",
  nextStage: "次のステージ",
  stopDone: "完了",
  stopCurrent: "学習中",
  stopLocked: "ロック中",
  quizStop: "チェック",
  progressSummary: "{total} レベル中 {done} 完了",
  modesTitle: "もっと練習する？",
  modeCharsTitle: "漢字を書く",
  modeCharsBody: "書き順を見て書く",
  modeDialogueTitle: "会話レッスン",
  modeDialogueBody: "聞いて話す",
  modeVocabTitle: "単語の音読",
  modeVocabBody: "単語と例文を読む",
  contentsTitle: "このレベルで学ぶこと",
  contentsChars: "漢字",
  contentsVocab: "単語",
  contentsIdiom: "成語のお話",
  dialogueTitle: "会話レッスン",
  dialogueBody: "レッスンを選んでください。レベルの進み具合には影響しません。",
  dialogueDone: "完了",
  dialogueStart: "はじめる",
  dialogueLesson: "第 {n} 課",
  menuTitle: "{name} のメニュー",
  menuOpen: "メニューを開く",
  menuLearning: "学習設定",
  menuMore: "その他",
  menuSync: "クラウド同期",
  menuSetupAgain: "学習者を設定し直す",
  menuAbout: "桐軒について",
  close: "閉じる",
  feedback: "問題を報告",
  support: "作者を応援",
  disclaimer: "免責事項とプライバシー",
};

const ko: HomeCopy = {
  ...en,
  greeting: "안녕, {name}!",
  todayLabel: "오늘의 레벨",
  reviewLabel: "이 레벨 다시 연습",
  levelN: "레벨 {n}",
  startToday: "오늘의 연습 시작",
  practiceAgain: "다시 연습하기",
  startQuiz: "점검 시작",
  allDoneTitle: "모든 레벨을 마쳤어요!",
  allDoneBody: "다시 연습하거나 회화 수업을 해 보세요.",
  minutes: "약 {n}분",
  streak: "{n}일 연속",
  streakAria: "{n}일 연속 학습",
  starsAria: "별 {n}개",
  mascotTip: "매일 조금씩, 중국어가 늘어요!",
  mascotAlt: "퉁쉬안 곰 안내자",
  backToToday: "오늘의 레벨로 돌아가기",
  pathTitle: "학습 경로",
  stageN: "{n}단계",
  prevStage: "이전 단계",
  nextStage: "다음 단계",
  stopDone: "완료",
  stopCurrent: "진행 중",
  stopLocked: "잠김",
  quizStop: "점검",
  progressSummary: "{total}개 중 {done}개 완료",
  modesTitle: "더 연습할까요?",
  modeCharsTitle: "한자 쓰기",
  modeCharsBody: "획순을 보고 따라 쓰기",
  modeDialogueTitle: "회화 수업",
  modeDialogueBody: "듣고 말하기",
  modeVocabTitle: "단어 소리 내어 읽기",
  modeVocabBody: "단어와 예문 읽기",
  contentsTitle: "이 레벨에서 배우는 것",
  contentsChars: "한자",
  contentsVocab: "단어",
  contentsIdiom: "성어 이야기",
  dialogueTitle: "회화 수업",
  dialogueBody: "수업을 고르세요. 레벨 진도에는 영향을 주지 않아요.",
  dialogueDone: "완료",
  dialogueStart: "시작",
  dialogueLesson: "제 {n} 과",
  menuTitle: "{name}의 메뉴",
  menuOpen: "메뉴 열기",
  menuLearning: "학습 설정",
  menuMore: "더 보기",
  menuSync: "클라우드 동기화",
  menuSetupAgain: "학습자 다시 설정",
  menuAbout: "퉁쉬안 소개",
  close: "닫기",
  feedback: "문제 신고",
  support: "제작자 후원",
  disclaimer: "면책 및 개인정보",
};

const es: HomeCopy = {
  ...en,
  greeting: "¡Hola, {name}!",
  todayLabel: "Nivel de hoy",
  reviewLabel: "Practicar este nivel otra vez",
  levelN: "Nivel {n}",
  startToday: "Empezar la práctica de hoy",
  practiceAgain: "Practicar otra vez",
  startQuiz: "Empezar el control",
  allDoneTitle: "¡Has terminado todos los niveles!",
  allDoneBody: "Elige un nivel para repasar o prueba una lección de conversación.",
  minutes: "Unos {n} min",
  streak: "{n} días seguidos",
  streakAria: "{n} días seguidos de estudio",
  starsAria: "{n} estrellas",
  mascotTip: "¡Un poco cada día mejora tu chino!",
  mascotAlt: "Oso guía de TongXuan",
  backToToday: "Volver al nivel de hoy",
  pathTitle: "Ruta de aprendizaje",
  stageN: "Etapa {n}",
  prevStage: "Etapa anterior",
  nextStage: "Etapa siguiente",
  stopDone: "Hecho",
  stopCurrent: "En curso",
  stopLocked: "Bloqueado",
  quizStop: "Control",
  progressSummary: "{done} de {total} niveles hechos",
  modesTitle: "¿Quieres practicar más?",
  modeCharsTitle: "Caracteres",
  modeCharsBody: "Mira los trazos y escribe",
  modeDialogueTitle: "Conversación",
  modeDialogueBody: "Escucha y habla",
  modeVocabTitle: "Palabras en voz alta",
  modeVocabBody: "Lee palabras y frases",
  contentsTitle: "En este nivel",
  contentsChars: "Caracteres",
  contentsVocab: "Palabras",
  contentsIdiom: "Historia de un modismo",
  dialogueTitle: "Lecciones de conversación",
  dialogueBody: "Elige una lección. No cambian tu progreso de niveles.",
  dialogueDone: "Hecho",
  dialogueStart: "Empezar",
  dialogueLesson: "Lección {n}",
  menuTitle: "Menú de {name}",
  menuOpen: "Abrir menú",
  menuLearning: "Ajustes de aprendizaje",
  menuMore: "Más",
  menuSync: "Sincronización en la nube",
  menuSetupAgain: "Configurar de nuevo al alumno",
  menuAbout: "Acerca de TongXuan",
  close: "Cerrar",
  feedback: "Informar de un problema",
  support: "Apoyar al autor",
  disclaimer: "Aviso legal y privacidad",
};

const COPY: Record<DisplayLang, HomeCopy> = { "zh-Hant": zhHant, "zh-Hans": zhHans, en, ja, ko, es };

export type HomeTranslate = (key: keyof HomeCopy, values?: Record<string, string | number>) => string;

export function homeTranslator(lang: DisplayLang): HomeTranslate {
  const table = COPY[lang] ?? zhHant;
  return (key, values) => {
    const template = table[key] ?? zhHant[key];
    if (!values) return template;
    return Object.entries(values).reduce((text, [name, value]) => text.split(`{${name}}`).join(String(value)), template);
  };
}
