export const copy = {
  "zh-Hant": {
    back: "返回",
    lessonPlayer: "課堂學習播放器",
    learnMode: "完整學習模式",
    fastTrackMode: "這一課我會了 · 快速挑戰",
    reviewMode: "到期複習模式",
    repairMode: "弱項補強模式",
    fastTrackBtn: "這一課我會了",
    fastTrackHint: "若您已掌握本課內容，可直接進行快速挑戰！",
    step: "步驟",
    of: "／",
    nextStep: "下一步",
    prevStep: "上一步",
    finishLesson: "完成今日課程",
    correct: "答對了！太棒了！",
    wrong: "再想想看，聽聽看提示喔！",
    listenAudio: "播放語音",
    recordStart: "按住開始開口跟讀",
    recordStop: "完成錄音",
    recording: "錄音中… 請大聲說出來",
    speakingSaved: "已記錄開口練習（獨立嘗試完成）",
    speechNote: "錄音僅在裝置端短暫處理，不會上傳或產生未驗證之分數評級。",
    skipWriting: "略過書寫（已掌握或選修）",
    showStroke: "播放筆順提示",
    tapToRevealScaffold: "點擊查看英文輔助說明",
    hideScaffold: "隱藏輔助說明",
    scaffoldFull: "完整顯示",
    scaffoldTap: "點擊查看",
    scaffoldHidden: "隱藏翻譯",
    scaffoldLabel: "母語鷹架",
    sessionSummaryTitle: "今日課堂結算",
    reviewCompletedTitle: "本輪複習完成",
    reviewCompletedNotice: "到期項目已記錄。原本的課程進度會保留在今日學習中。",
    sessionCompletedLabel: "今天的練習完成：",
    lessonPracticedLabel: "本課已練習：",
    masteryStatusLabel: "本課是否達到目前精熟條件：",
    nextReviewLabel: "下一次複習時間：",
    masteredYes: "已達成精熟條件",
    masteredInProgress: "練習中（需累積更多有效領域證據）",
    nextReviewTomorrow: "明天 (SRS 間隔複習)",
    sessionNotice: "注意：課堂完成代表已完成今日練習，精熟度將依各領域客觀作答證據另行獨立判定。",
    reviewStatusApproved: "內容已核准",
    reviewStatusReviewed: "內容已審閱",
    reviewStatusDraft: "自動生成草稿（待審核）",
    reviewStatusRejected: "內容未通過審核",
    activeRole: "活躍使用詞彙 (Active)",
    receptiveRole: "理解辨識詞彙 (Receptive)",
    exitTicketScore: "小挑戰得分",
    fastTrackPassed: "恭喜通過快速挑戰！已為您排入輕量複習排程。",
    fastTrackFailed: "部分領域需要再加強，正在為您安排精準補強練習…",
    domainListening: "聽力理解",
    domainRecognition: "生字認讀",
    domainVocabulary: "生詞理解",
    domainGrammar: "句型運用",
    domainWriting: "筆順書寫",
    domainSpeaking: "開口使用",
    retry: "重試",
    taskFailed: "任務操作失敗，請點擊重試",
    pleaseAnswerQuestion: "請先完成目前題目再繼續",
    noDueReviews: "目前沒有到期的複習項目",
    noDueReviewsDesc: "太棒了！所有進度都已掌握，暫時沒有需要檢索複習的生字或詞彙。",
    noDueReviewsNotice: "系統依據 SRS 遺忘曲線管理複習進度。當有生字到期時，會自動出現在今日複習中。",
    backToToday: "返回今日學習",
  },
  "zh-Hans": {
    back: "返回",
    lessonPlayer: "课堂学习播放器",
    learnMode: "完整学习模式",
    fastTrackMode: "这一课我会了 · 快速挑战",
    reviewMode: "到期复习模式",
    repairMode: "弱项补强模式",
    fastTrackBtn: "这一课我会了",
    fastTrackHint: "若您已掌握本课内容，可直接进行快速挑战！",
    step: "步骤",
    of: "／",
    nextStep: "下一步",
    prevStep: "上一步",
    finishLesson: "完成今日课程",
    correct: "答对了！太棒了！",
    wrong: "再想想看，听听看提示喔！",
    listenAudio: "播放语音",
    recordStart: "按住开始开口跟读",
    recordStop: "完成录音",
    recording: "录音中… 请大声说出来",
    speakingSaved: "已记录开口练习（独立尝试完成）",
    speechNote: "录音仅在设备端短暂处理，不会上传或产生未验证之分数评级。",
    skipWriting: "跳过书写（已掌握或选修）",
    showStroke: "播放笔顺提示",
    tapToRevealScaffold: "点击查看英文辅助说明",
    hideScaffold: "隐藏辅助说明",
    scaffoldFull: "完整显示",
    scaffoldTap: "点击查看",
    scaffoldHidden: "隐藏翻译",
    scaffoldLabel: "母语鹰架",
    sessionSummaryTitle: "今日课堂结算",
    reviewCompletedTitle: "本轮复习完成",
    reviewCompletedNotice: "到期项目已记录。原本的课程进度会保留在今日学习中。",
    sessionCompletedLabel: "今天的练习完成：",
    lessonPracticedLabel: "本课已练习：",
    masteryStatusLabel: "本课是否达到目前熟练条件：",
    nextReviewLabel: "下一次复习时间：",
    masteredYes: "已达成熟练条件",
    masteredInProgress: "练习中（需累积更多有效领域证据）",
    nextReviewTomorrow: "明天 (SRS 间隔复习)",
    sessionNotice: "注意：课堂完成代表已完成今日练习，熟练度将依各领域客观作答证据另行独立判定。",
    reviewStatusApproved: "内容已核准",
    reviewStatusReviewed: "内容已审阅",
    reviewStatusDraft: "自动生成草稿（待审核）",
    reviewStatusRejected: "内容未通过审核",
    activeRole: "活跃使用词汇 (Active)",
    receptiveRole: "理解辨识词汇 (Receptive)",
    exitTicketScore: "小挑战得分",
    fastTrackPassed: "恭喜通过快速挑战！已为您排入轻量复习排程。",
    fastTrackFailed: "部分领域需要再加强，正在为您安排精准补强练习…",
    domainListening: "听力理解",
    domainRecognition: "生字认读",
    domainVocabulary: "生词理解",
    domainGrammar: "句型运用",
    domainWriting: "笔顺书写",
    domainSpeaking: "开口使用",
    retry: "重试",
    taskFailed: "任务操作失败，请点击重试",
    pleaseAnswerQuestion: "请先完成当前题目再继续",
    noDueReviews: "目前没有到期的复习项目",
    noDueReviewsDesc: "太棒了！所有进度都已掌握，暂时没有需要检索复习的生字或词汇。",
    noDueReviewsNotice: "系统依据 SRS 遗忘曲线管理复习进度。当有生字到期时，会自动出现在今日复习中。",
    backToToday: "返回今日学习",
  },
  en: {
    back: "Back",
    lessonPlayer: "Lesson Player",
    learnMode: "Full Learning Mode",
    fastTrackMode: "I Know This · Fast Track",
    reviewMode: "Due Review Mode",
    repairMode: "Targeted Repair Mode",
    fastTrackBtn: "I know this lesson",
    fastTrackHint: "Already familiar with this lesson? Jump straight into the challenge!",
    step: "Step",
    of: "of",
    nextStep: "Next Step",
    prevStep: "Previous Step",
    finishLesson: "Finish Today's Lesson",
    correct: "Correct! Great job!",
    wrong: "Try again! Listen closely to the hint.",
    listenAudio: "Play Audio",
    recordStart: "Hold to record speaking",
    recordStop: "Stop recording",
    recording: "Recording… Speak clearly",
    speakingSaved: "Speaking practice recorded (Attempted Independently)",
    speechNote: "Audio is processed locally and discarded. No unverified speech percentage scores are generated.",
    skipWriting: "Skip writing (Already proficient / Optional)",
    showStroke: "Show stroke order",
    tapToRevealScaffold: "Tap to reveal English explanation",
    hideScaffold: "Hide explanation",
    scaffoldFull: "Full",
    scaffoldTap: "Tap to reveal",
    scaffoldHidden: "Hidden",
    scaffoldLabel: "Scaffold",
    sessionSummaryTitle: "Session Summary & Settlement",
    reviewCompletedTitle: "Review Complete",
    reviewCompletedNotice: "Your due reviews are recorded. Your current lesson progress remains in Today's Learning.",
    sessionCompletedLabel: "Today's practice completed:",
    lessonPracticedLabel: "Lesson practiced:",
    masteryStatusLabel: "Mastery criteria met:",
    nextReviewLabel: "Next review scheduled:",
    masteredYes: "Mastered (Verified by domain evidence)",
    masteredInProgress: "In Progress (Domain evidence accumulating)",
    nextReviewTomorrow: "Tomorrow (SRS Interval)",
    sessionNotice: "Note: Session completion marks daily practice. Domain mastery is independently evaluated from valid attempt evidence.",
    reviewStatusApproved: "Approved",
    reviewStatusReviewed: "Reviewed",
    reviewStatusDraft: "Generated draft (pending review)",
    reviewStatusRejected: "Rejected",
    activeRole: "Active Vocabulary",
    receptiveRole: "Receptive Vocabulary",
    exitTicketScore: "Exit Ticket Score",
    fastTrackPassed: "Fast Track Passed! Scheduled for lightweight SRS review.",
    fastTrackFailed: "Some domains need reinforcement. Launching targeted repair...",
    domainListening: "Listening",
    domainRecognition: "Recognition",
    domainVocabulary: "Vocabulary",
    domainGrammar: "Sentence Pattern",
    domainWriting: "Handwriting",
    domainSpeaking: "Speaking",
    retry: "Retry",
    taskFailed: "Task operation failed. Please retry.",
    pleaseAnswerQuestion: "Please answer the current question to continue",
    noDueReviews: "No due reviews right now",
    noDueReviewsDesc: "Great job! All items are up to date. There are no due SRS retrieval items.",
    noDueReviewsNotice: "The system schedules retrieval practice according to the SRS memory curve. Due items will automatically appear here.",
    backToToday: "Back to Today's Learning",
  },
  ja: {
    back: "戻る",
    lessonPlayer: "レッスンプレイヤー",
    learnMode: "標準学習モード",
    fastTrackMode: "このレッスンは知っています",
    reviewMode: "復習モード",
    repairMode: "弱点補強モード",
    fastTrackBtn: "このレッスンは知っています",
    fastTrackHint: "すでに知っている場合は、テストに直接挑戦できます！",
    step: "ステップ",
    of: "／",
    nextStep: "次へ",
    prevStep: "前へ",
    finishLesson: "今日の学習を完了",
    correct: "正解です！よくできました！",
    wrong: "もう一度挑戦してみましょう。",
    listenAudio: "音声を聞く",
    recordStart: "長押しで発音録音",
    recordStop: "録音終了",
    recording: "録音中… はっきりと発音してください",
    speakingSaved: "発音練習を記録しました（自主挑戦完了）",
    speechNote: "音声は端末内でのみ処理されます。",
    skipWriting: "書く練習をスキップ",
    showStroke: "筆順を表示",
    tapToRevealScaffold: "タップして解説を表示",
    hideScaffold: "解説を隠す",
    scaffoldFull: "全文表示",
    scaffoldTap: "タップで表示",
    scaffoldHidden: "非表示",
    scaffoldLabel: "言語サポート",
    sessionSummaryTitle: "学習完了サマリー",
    reviewCompletedTitle: "復習完了",
    reviewCompletedNotice: "期限の来た項目を記録しました。今日の学習の続きは保持されています。",
    sessionCompletedLabel: "本日の練習完了：",
    lessonPracticedLabel: "練習したレッスン：",
    masteryStatusLabel: "習熟判定：",
    nextReviewLabel: "次回復習日：",
    masteredYes: "習熟達成",
    masteredInProgress: "練習中（領域別の証拠を蓄積中）",
    nextReviewTomorrow: "明日 (SRS復習)",
    sessionNotice: "注：完了と習熟は別個に評価されます。",
    reviewStatusApproved: "承認済みコンテンツ",
    reviewStatusReviewed: "確認済みコンテンツ",
    reviewStatusDraft: "ドラフト",
    reviewStatusRejected: "却下されたコンテンツ",
    activeRole: "重要語彙 (Active)",
    receptiveRole: "理解語彙 (Receptive)",
    exitTicketScore: "テストスコア",
    fastTrackPassed: "テスト合格！復習がスケジュールされました。",
    fastTrackFailed: "一部の項目で補強が必要です。",
    domainListening: "リスニング",
    domainRecognition: "文字認識",
    domainVocabulary: "語彙",
    domainGrammar: "文型",
    domainWriting: "書く",
    domainSpeaking: "発音",
    retry: "再試行",
    taskFailed: "操作に失敗しました。再試行してください。",
    pleaseAnswerQuestion: "現在の問題に答えてから進んでください",
    noDueReviews: "現在、復習期日の項目はありません",
    noDueReviewsDesc: "素晴らしい！現在復習が必要な項目はありません。",
    noDueReviewsNotice: "SRS間隔に基づいて復習がスケジュールされます。",
    backToToday: "今日の学習に戻る",
  },
  ko: {
    back: "뒤로",
    lessonPlayer: "학습 플레이어",
    learnMode: "정규 학습 모드",
    fastTrackMode: "이 수업은 이미 알아요",
    reviewMode: "복습 모드",
    repairMode: "약점 보강 모드",
    fastTrackBtn: "이 수업은 이미 알아요",
    fastTrackHint: "이미 내용을 알고 있다면 바로 도전에 참여하세요!",
    step: "단계",
    of: "／",
    nextStep: "다음",
    prevStep: "이전",
    finishLesson: "오늘 학습 완료",
    correct: "정답입니다! 잘했어요!",
    wrong: "다시 한 번 생각해 보세요.",
    listenAudio: "음성 듣기",
    recordStart: "누르고 따라 읽기",
    recordStop: "녹음 완료",
    recording: "녹음 중… 큰 소리로 말해보세요",
    speakingSaved: "말하기 연습 기록 완료 (독립 시도 완료)",
    speechNote: "음성은 기기에서만 처리됩니다.",
    skipWriting: "쓰기 건너뛰기",
    showStroke: "획순 보기",
    tapToRevealScaffold: "탭하여 영어 설명 보기",
    hideScaffold: "설명 숨기기",
    scaffoldFull: "전체 표시",
    scaffoldTap: "탭하여 표시",
    scaffoldHidden: "숨기기",
    scaffoldLabel: "언어 지원",
    sessionSummaryTitle: "오늘의 학습 결과",
    reviewCompletedTitle: "복습 완료",
    reviewCompletedNotice: "복습 항목을 기록했어요. 오늘 학습의 진행 상태는 그대로 유지됩니다.",
    sessionCompletedLabel: "오늘 연습 완료:",
    lessonPracticedLabel: "연습한 수업:",
    masteryStatusLabel: "숙달 기준 충족:",
    nextReviewLabel: "다음 복습 일정:",
    masteredYes: "숙달 달성",
    masteredInProgress: "연습 중 (영역별 평가 진행 중)",
    nextReviewTomorrow: "내일 (SRS 간격 복습)",
    sessionNotice: "참고: 수업 완료와 숙달 달성은 별도로 평가됩니다.",
    reviewStatusApproved: "승인된 콘텐츠",
    reviewStatusReviewed: "검토된 콘텐츠",
    reviewStatusDraft: "초안",
    reviewStatusRejected: "검토에서 거부된 콘텐츠",
    activeRole: "핵심 어휘 (Active)",
    receptiveRole: "수용 어휘 (Receptive)",
    exitTicketScore: "도전 점수",
    fastTrackPassed: "도전 통과! 가벼운 복습이 예약되었습니다.",
    fastTrackFailed: "일부 영역의 보강이 필요합니다.",
    domainListening: "듣기",
    domainRecognition: "글자 인식",
    domainVocabulary: "어휘",
    domainGrammar: "문형",
    domainWriting: "쓰기",
    domainSpeaking: "말하기",
    retry: "다시 시도",
    taskFailed: "작업에 실패했습니다. 다시 시도해 주세요.",
    pleaseAnswerQuestion: "현재 문제를 먼저 완료하고 계속 진행하세요",
    noDueReviews: "현재 복습할 항목이 없습니다",
    noDueReviewsDesc: "훌륭합니다! 모든 항목이 최신 상태입니다.",
    noDueReviewsNotice: "SRS 주기에 따라 복습 항목이 자동으로 표시됩니다.",
    backToToday: "오늘의 학습으로 돌아가기",
  },
  es: {
    back: "Volver",
    lessonPlayer: "Reproductor de lección",
    learnMode: "Modo de aprendizaje",
    fastTrackMode: "Ya conozco esta lección",
    reviewMode: "Modo de repaso",
    repairMode: "Modo de refuerzo",
    fastTrackBtn: "Ya conozco esta lección",
    fastTrackHint: "¿Ya dominas esta lección? ¡Pasa directo al desafío!",
    step: "Paso",
    of: "de",
    nextStep: "Siguiente",
    prevStep: "Anterior",
    finishLesson: "Terminar lección de hoy",
    correct: "¡Correcto! ¡Muy bien!",
    wrong: "Inténtalo de nuevo.",
    listenAudio: "Escuchar audio",
    recordStart: "Mantén presionado para hablar",
    recordStop: "Terminar grabación",
    recording: "Grabando… habla con claridad",
    speakingSaved: "Práctica oral registrada (Intento independiente)",
    speechNote: "El audio se procesa localmente en el dispositivo.",
    skipWriting: "Omitir escritura",
    showStroke: "Ver orden de trazos",
    tapToRevealScaffold: "Toca para ver la explicación en inglés",
    hideScaffold: "Ocultar explicación",
    scaffoldFull: "Completo",
    scaffoldTap: "Tocar para ver",
    scaffoldHidden: "Oculto",
    scaffoldLabel: "Apoyo en tu idioma",
    sessionSummaryTitle: "Resumen de la lección",
    reviewCompletedTitle: "Repaso completado",
    reviewCompletedNotice: "Los repasos pendientes quedaron registrados. El progreso de la lección de hoy se conserva.",
    sessionCompletedLabel: "Práctica de hoy completada:",
    lessonPracticedLabel: "Lección practicada:",
    masteryStatusLabel: "Criterio de dominio alcanzado:",
    nextReviewLabel: "Próximo repaso programado:",
    masteredYes: "Dominado (Verificado por evidencia)",
    masteredInProgress: "En progreso (Acumulando evidencia)",
    nextReviewTomorrow: "Mañana (Repaso SRS)",
    sessionNotice: "Nota: Completar la sesión registra la práctica; el dominio se evalúa por separado.",
    reviewStatusApproved: "Contenido aprobado",
    reviewStatusReviewed: "Contenido revisado",
    reviewStatusDraft: "Borrador generado",
    reviewStatusRejected: "Contenido rechazado",
    activeRole: "Vocabulario activo",
    receptiveRole: "Vocabulario receptivo",
    exitTicketScore: "Puntaje del desafío",
    fastTrackPassed: "¡Desafío rápido aprobado! Programado para repaso ligero.",
    fastTrackFailed: "Algunas áreas necesitan refuerzo.",
    domainListening: "Comprensión auditiva",
    domainRecognition: "Reconocimiento",
    domainVocabulary: "Vocabulario",
    domainGrammar: "Patrón de oración",
    domainWriting: "Escritura",
    domainSpeaking: "Expresión oral",
    retry: "Reintentar",
    taskFailed: "Error en la operación. Intente nuevamente.",
    pleaseAnswerQuestion: "Por favor complete la pregunta actual para continuar",
    noDueReviews: "No hay repasos pendientes en este momento",
    noDueReviewsDesc: "¡Excelente! Todo está al día.",
    noDueReviewsNotice: "El sistema programa repasos espaciados (SRS) automáticamente.",
    backToToday: "Volver al aprendizaje de hoy",
  },
} as const;
