import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, BookOpen, CircleHelp, Gift, RefreshCw, Star, Target, Volume2, X } from "lucide-react";
import { BrowserSpeechSynthesisProvider } from "../lib/tts";
import { currentAnnotationMode, currentLearningLocale, useLocale } from "../lib/i18n";
import { Reward, PARENT_GATE_NOTE, isPasswordEntered } from "../lib/parentGate";

const API = import.meta.env.VITE_API_BASE ?? "";
const speechProvider = new BrowserSpeechSynthesisProvider();
type QueueItem = { id: string; character: string; source?: string; source_detail?: string; priority?: number };
type Child = { id: number; name: string };
type ReadingHint = { notation: string; notation_system: string };

async function api<T>(path: string, options?: RequestInit): Promise<T> {
  const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json" }, ...options });
  if (!response.ok) { let detail = "Request failed"; try { detail = (await response.json()).detail ?? detail; } catch { /* preserve fallback */ } throw new Error(detail); }
  return response.json();
}

type ChildHomeProps = { child: Child | null; childName: string; onOpenPractice: () => void; onOpenCurriculum?: () => void; onOpenSettings?: () => void };

export function ChildHomePage({ child, childName, onOpenPractice, onOpenCurriculum, onOpenSettings }: ChildHomeProps) {
  const { t } = useLocale();
  const [queue, setQueue] = useState<QueueItem[]>([]); const [points, setPoints] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [gateReward, setGateReward] = useState<Reward | null>(null); const [password, setPassword] = useState(""); const [gateError, setGateError] = useState(""); const [redeeming, setRedeeming] = useState(false); const [readingHint, setReadingHint] = useState<ReadingHint | null>(null); const lastFocused = useRef<HTMLElement | null>(null);
  const learningLocale = currentLearningLocale(); const annotationMode = currentAnnotationMode(); const script = learningLocale === "zh-TW" ? "TRADITIONAL" : "SIMPLIFIED"; const notationSystem = annotationMode === "AUTO" ? (learningLocale === "zh-TW" ? "ZHUYIN" : "PINYIN") : annotationMode === "BOPOMOFO" ? "ZHUYIN" : annotationMode === "PINYIN" ? "PINYIN" : "HIDDEN";

  async function refresh() { if (!child) { setLoading(false); return; } setLoading(true); setError(""); try { const [next, balance] = await Promise.all([api<QueueItem[]>(`/api/daily-queue?child_id=${child.id}`), api<any>(`/api/points?child_id=${child.id}`)]); setQueue(next); setPoints(balance); } catch (value) { setError(value instanceof Error ? value.message : "今日內容載入失敗"); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [child?.id]);
  const next = [...queue].sort((left, right) => (right.priority ?? 0) - (left.priority ?? 0))[0];
  useEffect(() => { setReadingHint(null); if (!next || notationSystem === "HIDDEN") return; const query = new URLSearchParams({ character: next.character, script }); void api<ReadingHint[]>(`/api/sprint-b/pronunciation?${query}`).then((readings) => setReadingHint(readings.find((reading) => reading.notation_system === notationSystem) ?? null)).catch(() => setReadingHint(null)); }, [next?.character, notationSystem, script]);
  useEffect(() => { if (!gateReward) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") closeGate(); }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [gateReward]);
  async function hearCharacter(character: string) { try { const payload = await api<any>("/api/tts/speak", { method: "POST", body: JSON.stringify({ text: character, text_kind: "character", locale: learningLocale, rate: 0.9 }) }); speechProvider.speak(payload); } catch (value) { setError(value instanceof Error ? value.message : "TTS unavailable"); } }
  function closeGate() { setGateReward(null); setPassword(""); setGateError(""); lastFocused.current?.focus(); }
  async function redeem() { if (!child || !gateReward) return; if (!isPasswordEntered(password)) { setGateError("請輸入家長密碼，交由後端驗證。"); return; } setRedeeming(true); setGateError(""); try { await api(`/api/points/redeem/${gateReward.id}?child_id=${child.id}`, { method: "POST", body: JSON.stringify({ parent_password: password }) }); setMessage(t("redeemSuccess", { name: gateReward.name })); closeGate(); await refresh(); } catch (value) { setGateError(value instanceof Error ? value.message : t("redeemError")); } finally { setRedeeming(false); } }

  return <main className="app-page child-home neo-home" aria-labelledby="child-home-title">
    <section className="neo-welcome"><div><p className="neo-overline">{t("todayPath")} <span className="neo-live-dot" /></p><h1 id="child-home-title">{t("hello", { name: childName })}</h1><p>{t("welcome")}</p></div><div className="neo-header-tools"><span className="neo-points"><Star size={15} fill="currentColor" />{points?.balance ?? "—"}</span><button className="neo-icon-button" aria-label={t("settings")} onClick={onOpenSettings}><CircleHelp size={20} /></button></div></section>
    {error && <div className="neo-alert" role="alert"><span>{error}</span><button onClick={() => void refresh()}><RefreshCw size={15}/>{t("retry")}</button></div>}
    {loading ? <section className="neo-skeleton" aria-busy="true" aria-label={t("loading")}><div /><div /><div /></section> : <>
    <section className={`neo-mission ${next ? "" : "neo-mission-empty"}`}><div className="neo-mission-top"><span className="neo-kicker"><Target size={15}/>{t("todayPath")}</span><span className="neo-mission-count">{queue.length ? queue.length : "0"}</span></div><div className="neo-mission-body"><div className="neo-mission-copy"><h2 id="daily-focus-title">{next ? t("nextUp") : t("noTasks")}</h2>{next ? <><div className="neo-character-row"><span className="neo-character" lang={script === "SIMPLIFIED" ? "zh-CN" : "zh-TW"}>{next.character}</span><button className="neo-sound" aria-label={t("hear")} onClick={() => void hearCharacter(next.character)}><Volume2 size={22}/></button></div>{readingHint && <p className="neo-reading"><strong>{readingHint.notation}</strong><span>{readingHint.notation_system === "ZHUYIN" ? "注音" : "Pinyin"}</span></p>}<p className="neo-source">{next.source_detail ?? next.source ?? t("practice")}</p></> : <p>{t("noTasksHint")}</p>}<button className="neo-start button-large" onClick={onOpenPractice}>{next ? t("start") : t("continue")}<ArrowUpRight size={20}/></button></div><div className="neo-mission-mark" aria-hidden="true"><span>01</span><small>READY</small></div></div></section>
      <section className="neo-section neo-queue" aria-labelledby="neo-queue-title"><div className="neo-section-head"><div><p className="neo-overline">{t("progress")}</p><h2 id="neo-queue-title">{t("todayPath")}</h2></div><button className="neo-link" onClick={onOpenPractice}>{t("seeAll")} <ArrowUpRight size={15}/></button></div>{queue.length ? <div className="neo-queue-list">{queue.slice(0, 4).map((entry, index) => <button key={`${entry.source}-${entry.id}`} className={`neo-queue-row ${index === 0 ? "is-current" : ""}`} onClick={onOpenPractice}><span className="neo-queue-index">{String(index + 1).padStart(2, "0")}</span><span className="neo-queue-glyph">{entry.character}</span><span className="neo-queue-label"><strong>{index === 0 ? t("continue") : t("nextUp")}</strong><small>{entry.source_detail ?? entry.source ?? t("practice")}</small></span><ArrowUpRight size={17}/></button>)}</div> : <div className="neo-empty"><BookOpen size={20}/>{t("noTasksHint")}</div>}</section>
      <section className="neo-quick-grid"><button onClick={onOpenCurriculum}><span className="neo-quick-number">01</span><BookOpen size={21}/><strong>{t("library")}</strong><small>{t("officialCourseTitle")}</small><ArrowUpRight size={16}/></button><button onClick={() => document.getElementById("neo-rewards")?.scrollIntoView({ behavior: "smooth" })}><span className="neo-quick-number">02</span><Gift size={21}/><strong>{t("rewards")}</strong><small>{t("points")}: {points?.balance ?? "—"}</small><ArrowUpRight size={16}/></button></section>
      <section className="neo-section neo-rewards" id="neo-rewards"><div className="neo-section-head"><div><p className="neo-overline">{t("rewards")}</p><h2>{t("points")}</h2></div><span className="neo-points neo-points-large"><Star size={16} fill="currentColor" />{points?.balance ?? "—"}</span></div>{points?.rewards?.length ? <div className="neo-reward-list">{points.rewards.slice(0, 3).map((reward: Reward) => <article key={reward.id} className="neo-reward-row"><span className="neo-reward-icon"><Gift size={20}/></span><span><strong>{reward.name}</strong><small>{reward.description ?? t("continue")}</small></span><span className="neo-cost"><Star size={13} fill="currentColor" />{reward.cost}</span><button aria-label="兌換選擇的獎勵" disabled={!child || (points?.balance ?? 0) < reward.cost} onClick={(event) => { lastFocused.current = event.currentTarget; setGateReward(reward); setGateError(""); }}><ArrowUpRight size={17}/></button></article>)}</div> : <div className="neo-empty"><Gift size={20}/>{t("rewardEmpty")}</div>}</section>
    </>}
    {gateReward && <div className="neo-modal-backdrop" role="presentation"><section className="neo-modal" role="dialog" aria-modal="true" aria-labelledby="reward-dialog-title"><button className="neo-modal-close" aria-label={`${t("close")}${t("parentConfirm")}視窗`} onClick={closeGate} disabled={redeeming}><X size={20}/></button><p className="neo-overline">{t("parentConfirm")}</p><h2 id="reward-dialog-title">{t("redeemTitle", { name: gateReward.name })}</h2><p>{t("parentAuth")}</p><label htmlFor="parent-password">{t("parentPassword")}</label><input id="parent-password" autoFocus type="password" value={password} disabled={redeeming} onChange={(event) => setPassword(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void redeem(); }} placeholder={t("enterParentPassword")} />{gateError && <p className="neo-field-error" role="alert">{gateError}</p>}<p className="neo-modal-note">{PARENT_GATE_NOTE}</p><div className="neo-modal-actions"><button onClick={closeGate} disabled={redeeming}>{t("cancel")}</button><button className="neo-start" onClick={() => void redeem()} disabled={redeeming || !password.trim()}>{redeeming ? t("verifying") : t("confirmRedeem")}</button></div></section></div>}
    {message && <p className="sr-status" role="status">{message}</p>}
  </main>;
}
