import { type CSSProperties, type PointerEvent, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, CalendarDays, Crown, House, Moon, PenLine, Puzzle, Sparkles, Speech, Star, Sun, UserRound, Volume2 } from "lucide-react";

/** Static concept page: weekly timeline and a calm daily learning card. */
export function DesignPreviewBPage() {
  const [darkMode, setDarkMode] = useState(false);
  const [dayIndex, setDayIndex] = useState(1);
  const [calendarOpen, setCalendarOpen] = useState(false);
  const [dragX, setDragX] = useState(0);
  const [dragging, setDragging] = useState(false);
  const [pointerStart, setPointerStart] = useState<number | null>(null);
  const [tilt, setTilt] = useState({ x: 0, y: 0 });
  const days = [
    { date: "9/21", count: "8/15", state: "done", label: "週一", text: "你", hint: "you · nǐ", stars: 3 },
    { date: "9/22", count: "15/15", state: "passed", label: "週二", text: "學", hint: "learn · xué", stars: 2 },
    { date: "9/23", count: "0/15", state: "today", label: "今天", text: "學校", hint: "school · xuéxiào", stars: 1 },
    { date: "9/24", count: "0/15", state: "upcoming", label: "週四", text: "老師", hint: "teacher · lǎoshī", stars: 0 },
    { date: "9/25", count: "0/15", state: "upcoming", label: "週五", text: "朋友", hint: "friend · péngyou", stars: 0 },
    { date: "9/26", count: "BOSS", state: "boss", label: "考試日", text: "第一關", hint: "5 日學習檢定", stars: 0 },
  ];
  const day = days[dayIndex];
  const setDay = (index: number) => setDayIndex(Math.max(0, Math.min(days.length - 1, index)));
  const onPointerDown = (event: PointerEvent<HTMLButtonElement>) => { setPointerStart(event.clientX); setDragging(true); event.currentTarget.setPointerCapture(event.pointerId); };
  const onPointerMove = (event: PointerEvent<HTMLButtonElement>) => { const bounds = event.currentTarget.getBoundingClientRect(); setTilt({ x: ((event.clientY - bounds.top) / bounds.height - .5) * -7, y: ((event.clientX - bounds.left) / bounds.width - .5) * 9 }); if (pointerStart !== null) setDragX(Math.max(-90, Math.min(90, event.clientX - pointerStart))); };
  const onPointerUp = () => { if (Math.abs(dragX) > 45) setDay(dayIndex + (dragX < 0 ? 1 : -1)); setDragX(0); setPointerStart(null); setDragging(false); setTilt({ x: 0, y: 0 }); };
  return <main className={`playroom-preview simple-playroom ${darkMode ? "is-dark" : ""}`}>
    <header className="playroom-top"><button className="playroom-avatar" aria-label="切換學習者">小</button><div><span className="playroom-greeting">{day.label} · 第 12 天</span><h1>嗨，小安 <span>✦</span></h1></div><div className="playroom-tools"><span><Star size={15} fill="currentColor"/> 120</span><button aria-label={darkMode ? "切換淺色護眼模式" : "切換深色護眼模式"} onClick={() => setDarkMode((value) => !value)}>{darkMode ? <Sun size={19}/> : <Moon size={19}/>}</button></div></header>
    <section className="study-timeline" aria-label="本週學習進度"><div className="timeline-heading"><span><CalendarDays size={15}/> 本週學習量</span><button onClick={() => setCalendarOpen((value) => !value)}><CalendarDays size={14}/> 查看月份戰績</button></div><div className="timeline-rail"><button className="timeline-arrow" aria-label="上一天" disabled={dayIndex === 0} onClick={() => setDay(dayIndex - 1)}><ArrowLeft size={16}/></button><div className="timeline-days">{days.map((item, index) => <button key={item.date} className={`timeline-day ${item.state} ${index === dayIndex ? "selected" : ""}`} onClick={() => setDay(index)}><span>{item.date}</span>{item.state === "boss" ? <Crown size={16}/> : item.state === "passed" ? <Star size={15} fill="currentColor"/> : <b>{item.count}</b>}</button>)}</div><button className="timeline-arrow" aria-label="下一天" disabled={dayIndex === days.length - 1} onClick={() => setDay(dayIndex + 1)}><ArrowRight size={16}/></button></div>{calendarOpen && <div className="month-preview"><div><strong>2026 年 9 月</strong><small>完成一天就留下金星</small></div><div className="month-grid">{Array.from({ length: 30 }, (_, index) => String(index + 1)).map((date) => <span key={date} className={date === "21" || date === "22" ? "month-cleared" : ""}>{date}{(date === "21" || date === "22") && <Star size={10} fill="currentColor"/>}</span>)}</div></div>}</section>
    <section className={`playroom-stage card-stage ${day.state === "boss" ? "boss-stage" : ""}`} aria-labelledby="preview-quest-title"><div className="playroom-cloud cloud-a"/><div className="playroom-cloud cloud-b"/><div className="ambient-orbit orbit-one"/><div className="ambient-orbit orbit-two"/><div className="card-stage-head"><span className="playroom-label">{day.state === "boss" ? <><Crown size={14}/> 第 1 關 BOSS 考試</> : <><Sparkles size={14}/> {day.date} 的學習卡</>}</span><span>{day.state === "boss" ? "準備挑戰" : day.count}</span></div><button className="card-arrow card-arrow-left" aria-label="上一張學習卡" disabled={dayIndex === 0} onClick={() => setDay(dayIndex - 1)}><ArrowLeft size={19}/></button><button className="card-arrow card-arrow-right" aria-label="下一張學習卡" disabled={dayIndex === days.length - 1} onClick={() => setDay(dayIndex + 1)}><ArrowRight size={19}/></button><div className="card-stack"><span className="card-stack-shadow card-stack-shadow-back"/><span className="card-stack-shadow card-stack-shadow-front"/><button className={`learning-card ${dragging ? "is-dragging" : ""}`} style={{ "--drag-x": `${dragX}px`, "--tilt-x": `${tilt.x}deg`, "--tilt-y": `${tilt.y}deg` } as CSSProperties} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp} onPointerLeave={() => !dragging && setTilt({ x: 0, y: 0 })} onClick={() => undefined}><div className="card-3d-icon"><span>{day.text}</span><span className="card-audio" aria-label={`播放${day.text}的發音`}><Volume2 size={18}/></span></div><div className="learning-card-copy"><span>{day.state === "boss" ? "完成 5 天後解鎖" : `第 ${day.date} 天 · ${day.hint}`}</span><h2 id="preview-quest-title">{day.text}</h2><div className="card-star-row" aria-label={`${day.stars} 顆星`}><Star size={17} fill={day.stars >= 1 ? "currentColor" : "none"}/><Star size={17} fill={day.stars >= 2 ? "currentColor" : "none"}/><Star size={17} fill={day.stars >= 3 ? "currentColor" : "none"}/><Star size={17} fill="none"/><Star size={17} fill="none"/></div><small>{day.state === "boss" ? "錯題會自動回到練習清單" : `已完成 ${day.stars} / 5 個能力`}</small></div></button></div><span className="card-drag-hint"><ArrowLeft size={13}/> 左右拖曳切換學習日 <ArrowRight size={13}/></span></section>
    <section className="card-skills"><span>能力進度</span><div><b><Speech size={15}/> 會念</b><b><PenLine size={15}/> 會寫</b><b><Puzzle size={15}/> 會應用</b></div></section><p className="simple-playroom-hint"><BookOpen size={16}/> 卡住時先完成本週欠缺的學習量，才能解鎖下一週。</p>
    <nav className="playroom-tabs"><button className="active"><House/><span>今天</span></button><button><Sparkles/><span>練習</span></button><button><BookOpen/><span>課程</span></button><button><UserRound/><span>我的</span></button></nav>
  </main>;
}
