import { DisplayLang } from "./types";
export const UI_TEXT: Record<DisplayLang, Record<string, string>> = {
  "zh-Hant": {
    morning: "早安",
    weekN: "第 {n} 週",
    menu: "選單",
    brandTitle: "桐軒中文",
    brandEnSubtitle: "TONGXUAN",
    levelProgressSub: "🎯 第 {n} 關 · 挑戰中 🔄",
    pinkyPactChip: "🤙 打勾勾約定：{current}/{total} 天",
    myAchievements: "我的成就",
    draftContentNotice: "下方關卡是桐軒自編示範內容，尚未納入官方課程。",
    openVerifiedCurriculum: "查看官方課程",
    startValidatedSession: "開始今日學習",
    sessionProfileMissing: "找不到這位學習者的正式課程檔案，請家長先從課程頁新增相同名稱的學習者。",
    rewardsShop: "獎勵兌換舖",
    settings: "設定",
    beginnerChipOn: "初學標音 · 開啟",
    beginnerChipOff: "純漢字 · 閱讀",
    beginnerModeLabel: "初學者標音模式 (全字標音)",
    beginnerModeActive: "全螢幕中文字均加上注音/拼音",
    beginnerModeInactive: "純漢字閱讀挑戰模式",
    eyeCareMode: "護眼模式",
    eyeCareDark: "深色低藍光",
    eyeCareLight: "白天模式",
    eyeCareDarkShort: "🌙 開啟",
    eyeCareLightShort: "☀️ 白天",
    scriptModeLabel: "學習字體與拼讀",
    scriptZhuyin: "繁體注音",
    scriptPinyin: "簡體拼音",
    scriptDual: "繁+簡雙軌",
    scriptZhuyinShort: "繁體",
    scriptPinyinShort: "簡體",
    scriptDualShort: "繁+簡",
    displayLangLabel: "介面顯示語言",
    phoneticLabel: "生字標音顯示",
    phoneticAssistLabel: "閱讀標音輔助",
    phoneticShow: "顯示標音",
    phoneticHide: "隱藏標音 (識字挑戰)",
    assistZhuyinShort: "注音",
    assistPinyinShort: "拼音",
    assistOffShort: "隱藏",
    handModeLabel: "習慣用手切換",
    handRight: "✋ 右手",
    handLeft: "🤚 左手",
    stageN: "🚩 第 {n} 階段",
    sprintDayN: "第 {n} 日",
    milestoneReview: "全冊總複習",
    stageQuiz: "綜合測驗",
    passedStatus: "已及格",
    evalStatus: "驗收",
    voiceGuide: "語音導讀",
    fullReadAloud: "全篇朗讀",
    playSentence: "播放單句",
    repeatSentence: "🎙️ 復誦跟讀",
    doneRecording: "⏹️ 完成跟讀",
    communityFooterText: "☕ 桐軒中文為免費開源專案 · 歡迎回饋使用體驗與建議！",
    betaDisclaimerLink: "⚠️ 目前為公開測試版 (Beta) · 點此查看《免責聲明與隱私條款》",
    feedbackBtn: "問題與建議回報",
    sponsorBtn: "請作者喝咖啡",
    switchUser: "👤 切換學習者帳號",
    parentZone: "進入家長管理後台",
    today: "今日",
    lessonDay: "{day} 課程",
    lessonDuration: "⏱️ 約 {min} 分鐘",
    readAloud: "課文朗讀",
    cardStrokeTitle: "生字 · 聽說讀寫",
    cardVocabTitle: "生詞 · 認讀造句",
    cardIdiomTitle: "成語 · 故事閱讀",
    cardStrokeDualHint: "田字格筆順 · 聽說讀寫 5 步全循環",
    cardStrokeSingleHint: "田字格筆順描紅 · 點擊進入全循環練字",
    cardVocabHint: "生活常見高頻詞彙 · 點擊認讀聽發音",
    cardIdiomHint: "成語典故故事與情境生活應用",
    exitClass: "退出教室",
    step1Title: "🌟 第一步：看一看 · 聽音認生字",
    step2Title: "✍️ 第二步：寫一寫 · 筆順描紅練習",
    step3Title: "📝 第三步：記一記 · 記憶默寫挑戰",
    step4Title: "🗣️ 第四步：讀一讀 · 字義組詞造句",
    step5Title: "🎯 第五步：測一測 · 課後通關測驗",
    traceCountLabel: "剩餘練習",
    traceOnceBtn: "✍️ 寫好了",
    traceCountDone: "🎉 書寫階段已完成！",
    dictationHint: "憑記憶在田字格內書寫，忘記可點 💡 提示！",
    dictationClear: "清除",
    dictationToggleHint: "提示",
    dictationSubmit: "寫好了",
    dictationPassed: "太棒了！默寫成功！",
    standardSound: "發音",
    speakBtn: "開口說話 (錄音評測)",
    sentencePlay: "播放課文朗讀",
    prevStep: "上一步",
    nextStep: "下一步",
    finishLessonBtn: "完成今日課程 🎉",
    rewardClaimReturn: "領取獎勵並返回",
    traceHint: "請用手指在田字格內跟著筆畫描寫！",
    traceBothTip: "繁體「{t}」{ts}畫 · 簡體「{s}」{ss}畫",
    traceSameTip: "「{c}」為繁簡同體字，共 {n} 畫（部首：{r}）",
    speakInstruction: "請大聲讀出標準發音與聲調！",
    praiseGood: "讀得非常棒！發音很標準！",
    chestTitle: "🎁 週日神秘寶箱",
    chestSub: "每週日打開寶箱，領取神秘大禮物！",
    normalChestTitle: "📦 寶箱 1：通關大寶箱",
    normalChestCond: "本週通關 6 天即可開啟（不需連續）",
    streakChestTitle: "👑 寶箱 2：全勤王者寶箱",
    streakChestCond: "連續 6 天及時通關，週日多開 1 個大寶箱！",
    rewardText: "獎勵：⭐ +10 星 + 🎁 識字徽章",
    rewardStreakText: "獎勵：⭐ 額外 +10 星 + 👑 王者皇冠",
    openChest: "🎁 點擊開箱",
    openKingChest: "👑 點擊打開王者寶箱",
    needKeys: "還差 {n} 支鑰匙",
    needStreak: "連續打卡還差 {n} 天",
    chestFooter: "💡 每天認真學習，週日就能同時抱走 2 個大寶箱 喔！",
    parentGateTitle: "家長管理專區安全鎖",
    parentGateDesc: "為保護小朋友專注學習，請回答算術問題進入家長後台：",
    parentDashboardTitle: "👨‍👩‍👧 家長學習管理後台",
    parentDashboardDesc: "已驗證家長身份。在此配置每日學習量、教材主線與防沉迷時間：",
    parentPlanLabel: "🎯 每日學習量與目標時長",
    parentCurriculumLabel: "📚 僑委會主線教材冊次",
    saveSettings: "儲存學習設定",
    aboutModalTitle: "桐軒中文 · 關於、藍圖與使用條款",
    aboutModalSub: "專為海外兒童與初學者量身打造 · 溫暖、趣味、系統化的華語全景學習平臺",
    tabAbout: "🌟 理念與特色",
    tabRoadmap: "🗺️ 全景進階路線與檢定目標",
    tabLegal: "⚖️ 教材出處與版權聲明",
    tabDisclaimer: "📜 測試版與免責聲明",
    aboutFeat1Title: "田字格分階段書寫引擎",
    aboutFeat1Desc: "提示會依孩子的書寫狀態逐步減少，並在需要時安排針對性重試。",
    aboutFeat2Title: "繁簡注拼雙軌並進",
    aboutFeat2Desc: "同步支援臺灣注音符號（ㄅㄆㄇ）與國際漢語拼音（pīnyīn），繁簡同字或異字自動對照，無縫切換。",
    aboutFeat3Title: "桐軒自編示範課程",
    aboutFeat3Desc: "本頁保留的關卡與生字是桐軒自編示範；已驗證的官方課程範圍請查看學習地圖。",
    aboutFeat4Title: "正向激勵與護眼承諾",
    aboutFeat4Desc: "無噪音式手遊誘導，透過星星打卡與週日開箱微習慣，並提供低藍光深色護眼模式呵護視力。",
    disclaimerTitle: "📜 公開測試版 (Beta) 免責聲明與隱私條款",
    disclaimerPoint1Title: "⚠️ 公開測試版與進度保存風險：",
    disclaimerPoint1Desc: "本專案目前處於公開 Beta 測試與持續改版階段。當系統升級、發布新功能或您清除瀏覽器快取時，儲存於您設備本地的學習進度（如金幣、星星、答錯記錄、兌換券）可能隨時被重置或調整。本系統不保證歷史資料的永久保存。",
    disclaimerPoint2Title: "🔒 本地優先架構與匿名學習統計說明：",
    disclaimerPoint2Desc: "本系統採 Local-First 本地架構，嚴格保護兒少隱私，不收集姓名、Email、電話等個人身分資料（PII）。系統僅收集去識別化之匿名學習進度事件（如關卡完成次數、難度流暢度），僅用於改進教材與提升教學體驗。所有個人學習進度 100% 儲存於您設備本地瀏覽器中。",
    disclaimerPoint3Title: "📚 非正式教育機構與學習成效免責：",
    disclaimerPoint3Desc: "本系統為個人開發之自主自學輔助工具，非教育部或官方認證之正式學校機構。本系統不對任何使用者的識字速度、發音標準度、考試成績或特定學習結果提供任何形式之保證。",
    disclaimerPoint4Title: "☕ 開源與贊助性質：",
    disclaimerPoint4Desc: "本專案程式碼採 MIT 授權開源發布。請作者喝咖啡（Sponsor）屬於個人自願贊助與鼓勵性質，不構成任何商業契約、付費訂閱服務或專屬客服義務。",
    disclaimerFooter: "桐軒中文恪守兒少隱私安全規範 · 感謝所有測試家長與教育工作者的理解與支持",
    officialCurriculumBadge: "官方課綱 · 授權審查中",
    curriculumObjectives: "本課學習目標",
    practiceTargetsLabel: "核心練習重點",
    domainsLabel: "涵蓋學習領域",
    extraPracticeSectionTitle: "桐軒自編示範練習區",
    extraPracticeSectionNote: "此區為桐軒早期自編原型內容，供延伸體驗與筆順演練，非僑委會官方教材。",
    listeningDomain: "聽力",
    speakingDomain: "口說",
    recognitionDomain: "識字",
    phoneticsDomain: "標音",
    pronunciationDomain: "發音",
    vocabularyDomain: "語彙",
    grammarDomain: "語法",
    writingDomain: "書寫",
    readingDomain: "閱讀",
    upcomingLessonBadge: "後續課程",
    upcomingLessonNotice: "此課為後續課綱內容 · 請先完成今日課程",
    backToTodayLesson: "返回今日課程",
    lessonMasteredBanner: "🎉 本課已掌握通關！",
    todayGoalCompleted: "今日學習已達成 🎉",
    startReviewSession: "開始複習任務 ({n} 字待複習)",
    nextLessonComingSoon: "👉 下一課《{title}》即將推出，敬請期待！",
    draftTasksTitle: "關卡 {n} 自編練習卡片"
  },
  "zh-Hans": {
    morning: "早安",
    weekN: "第 {n} 周",
    menu: "菜单",
    brandTitle: "童轩中文",
    brandEnSubtitle: "TONGXUAN",
    levelProgressSub: "🎯 第 {n} 关 · 挑战中 🔄",
    pinkyPactChip: "🤙 打勾勾约定：{current}/{total} 天",
    myAchievements: "我的成就",
    draftContentNotice: "下方关卡是童轩自编示范内容，尚未纳入官方课程。",
    openVerifiedCurriculum: "查看官方课程",
    startValidatedSession: "开始今日学习",
    sessionProfileMissing: "找不到这位学习者的正式课程档案，请家长先从课程页新增相同名称的学习者。",
    rewardsShop: "奖励兑换铺",
    settings: "设置",
    beginnerChipOn: "初学标音 · 开启",
    beginnerChipOff: "纯汉字 · 阅读",
    beginnerModeLabel: "初学者标音模式 (全字标音)",
    beginnerModeActive: "全屏幕中文字均加上注音/拼音",
    beginnerModeInactive: "纯汉字阅读挑战模式",
    eyeCareMode: "护眼模式",
    eyeCareDark: "深色低蓝光",
    eyeCareLight: "白天模式",
    eyeCareDarkShort: "🌙 开启",
    eyeCareLightShort: "☀️ 白天",
    scriptModeLabel: "学习字体与拼读",
    scriptZhuyin: "繁体注音",
    scriptPinyin: "简体拼音",
    scriptDual: "繁+简双轨",
    scriptZhuyinShort: "繁体",
    scriptPinyinShort: "简体",
    scriptDualShort: "繁+简",
    displayLangLabel: "界面显示语言",
    phoneticLabel: "生字标音显示",
    phoneticAssistLabel: "阅读标音辅助",
    phoneticShow: "显示标音",
    phoneticHide: "隐藏标音 (识字挑战)",
    assistZhuyinShort: "注音",
    assistPinyinShort: "拼音",
    assistOffShort: "隐藏",
    handModeLabel: "习惯用手切换",
    handRight: "✋ 右手",
    handLeft: "🤚 左手",
    stageN: "🚩 第 {n} 阶段",
    sprintDayN: "第 {n} 日",
    milestoneReview: "全册总复习",
    stageQuiz: "综合测验",
    passedStatus: "已及格",
    evalStatus: "验收",
    voiceGuide: "语音导读",
    fullReadAloud: "全篇朗读",
    playSentence: "播放单句",
    repeatSentence: "🎙️ 复诵跟读",
    doneRecording: "⏹️ 完成跟读",
    communityFooterText: "☕ 童轩中文为免费开源项目 · 欢迎反馈使用体验与建议！",
    betaDisclaimerLink: "⚠️ 目前为公开测试版 (Beta) · 点此查看《免责声明与隐私条款》",
    feedbackBtn: "问题与建议回报",
    sponsorBtn: "请作者喝咖啡",
    switchUser: "👤 切换学习者账号",
    parentZone: "进入家长管理后台",
    today: "今日",
    lessonDay: "{day} 课程",
    lessonDuration: "⏱️ 约 {min} 分钟",
    readAloud: "课文朗读",
    cardStrokeTitle: "生字 · 听说读写",
    cardVocabTitle: "生词 · 认读造句",
    cardIdiomTitle: "成语 · 故事阅读",
    cardStrokeDualHint: "田字格笔顺 · 听说读写 5 步全循环",
    cardStrokeSingleHint: "田字格笔顺描红 · 点击进入全循环练字",
    cardVocabHint: "生活常见高频词汇 · 点击认读听发音",
    cardIdiomHint: "成语典故故事与情境生活应用",
    exitClass: "退出教室",
    step1Title: "🌟 第一步：看一看 · 听音认生字",
    step2Title: "✍️ 第二步：写一写 · 笔顺描红练习",
    step3Title: "📝 第三步：记一记 · 记忆默写挑战",
    step4Title: "🗣️ 第四步：读一读 · 字义组词造句",
    step5Title: "🎯 第五步：测一测 · 课后通关测验",
    traceCountLabel: "剩余练习",
    traceOnceBtn: "✍️ 写好了",
    traceCountDone: "🎉 书写阶段已完成！",
    dictationHint: "凭记忆在田字格内书写，忘记可点 💡 提示！",
    dictationClear: "清除",
    dictationToggleHint: "提示",
    dictationSubmit: "写好了",
    dictationPassed: "太棒了！默写成功！",
    standardSound: "发音",
    speakBtn: "开口说话 (录音评测)",
    sentencePlay: "播放课文朗读",
    prevStep: "上一步",
    nextStep: "下一步",
    finishLessonBtn: "完成今日课程 🎉",
    rewardClaimReturn: "领取奖励并返回",
    traceHint: "请用手指在田字格内跟着笔画描写！",
    traceBothTip: "繁体「{t}」{ts}画 · 简体「{s}」{ss}画",
    traceSameTip: "「{c}」为繁简同体字，共 {n} 画（部首：{r}）",
    speakInstruction: "请大声读出标准发音与声调！",
    praiseGood: "读得非常棒！发音很标准！",
    chestTitle: "🎁 周日神秘宝箱",
    chestSub: "每周日打开宝箱，领取神秘大礼物！",
    normalChestTitle: "📦 宝箱 1：通关大宝箱",
    normalChestCond: "本周通关 6 天即可开启（不需连续）",
    streakChestTitle: "👑 宝箱 2：全勤王者宝箱",
    streakChestCond: "连续 6 天及时通关，周日多开 1 个大宝箱！",
    rewardText: "奖励：⭐ +10 星 + 🎁 识字徽章",
    rewardStreakText: "奖励：⭐ 额外 +10 星 + 👑 王者皇冠",
    openChest: "🎁 点击开箱",
    openKingChest: "👑 点击打开王者宝箱",
    needKeys: "还差 {n} 支钥匙",
    needStreak: "连续打卡还差 {n} 天",
    chestFooter: "💡 每天认真学习，周日就能同时抱走 2 个大宝箱 喔！",
    parentGateTitle: "家长管理专区安全锁",
    parentGateDesc: "为保护小朋友专注学习，请回答算术问题进入家长后台：",
    parentDashboardTitle: "👨‍👩‍👧 家长学习管理后台",
    parentDashboardDesc: "已验证家长身份。在此配置每日学习量、教材主线与防沉迷时间：",
    parentPlanLabel: "🎯 每日学习量与目标时长",
    parentCurriculumLabel: "📚 侨委会主线教材册次",
    saveSettings: "保存学习设置",
    aboutModalTitle: "童轩中文 · 关于、蓝图与使用条款",
    aboutModalSub: "专为海外儿童与初学者量身打造 · 温暖、趣味、系统化的华语全景学习平台",
    tabAbout: "🌟 理念与特色",
    tabRoadmap: "🗺️ 全景进阶路线与检定目标",
    tabLegal: "⚖️ 教材出处与版权声明",
    tabDisclaimer: "📜 测试版与免责声明",
    aboutFeat1Title: "田字格分阶段书写引擎",
    aboutFeat1Desc: "提示会根据孩子的书写状态逐步减少，并在需要时安排针对性重试。",
    aboutFeat2Title: "繁简注拼双轨并进",
    aboutFeat2Desc: "同步支持台湾注音符号（ㄅㄆㄇ）与国际汉语拼音（pīnyīn），繁简同字或异字自动对照，无缝切换。",
    aboutFeat3Title: "童轩自编示范课程",
    aboutFeat3Desc: "本页保留的关卡与生字是童轩自编示范；已验证的官方课程范围请查看学习地图。",
    aboutFeat4Title: "正向激励与护眼承诺",
    aboutFeat4Desc: "无噪音式手游诱导，通过星星打卡与周日开箱微习惯，并提供低蓝光深色护眼模式呵护视力。",
    disclaimerTitle: "📜 公开测试版 (Beta) 免责声明与隐私条款",
    disclaimerPoint1Title: "⚠️ 公开测试版与进度保存风险：",
    disclaimerPoint1Desc: "本项目目前处于公开 Beta 测试与持续改版阶段。当系统升级、发布新功能或您清除浏览器缓存时，储存于您设备本地的学习进度（如金币、星星、答错记录、兑换券）可能随时被重置或调整。本系统不保证历史数据的永久保存。",
    disclaimerPoint2Title: "🔒 本地优先架构与匿名学习统计说明：",
    disclaimerPoint2Desc: "本系统采 Local-First 本地架构，严格保护少儿隐私，不收集姓名、Email、电话等个人身份资料（PII）。系统仅收集去识别化之匿名学习进度事件（如关卡完成次数、难度流畅度），仅用于改进教材与提升教学体验。所有个人学习进度 100% 储存于您设备本地浏览器中。",
    disclaimerPoint3Title: "📚 非正式教育机构与学习成效免责：",
    disclaimerPoint3Desc: "本系统为个人开发之自主自学辅助工具，非教育部或官方认证之正式学校机构。本系统不对任何使用者的识字速度、发音标准度、考试成绩或特定学习结果提供任何形式之保证。",
    disclaimerPoint4Title: "☕ 开源与赞助性质：",
    disclaimerPoint4Desc: "本项目代码采 MIT 授权开源发布。请作者喝咖啡（Sponsor）属于个人自愿赞助与鼓励性质，不构成任何商业契约、付费订阅服务或专属客服义务。",
    disclaimerFooter: "童轩中文恪守儿少隐私安全规范 · 感谢所有测试家长与教育工作者的理解与支持",
    officialCurriculumBadge: "官方课纲 · 授权审查中",
    curriculumObjectives: "本课学习目标",
    practiceTargetsLabel: "核心练习重点",
    domainsLabel: "涵盖学习领域",
    extraPracticeSectionTitle: "童轩自编示范练习区",
    extraPracticeSectionNote: "此区为童轩早期自编原型内容，供延伸体验与笔顺演练，非侨委会官方教材。",
    listeningDomain: "听力",
    speakingDomain: "口语",
    recognitionDomain: "识字",
    phoneticsDomain: "标音",
    pronunciationDomain: "发音",
    vocabularyDomain: "词汇",
    grammarDomain: "语法",
    writingDomain: "书写",
    readingDomain: "阅读",
    upcomingLessonBadge: "后续课程",
    upcomingLessonNotice: "此课为后续课纲内容 · 请先完成今日课程",
    backToTodayLesson: "返回今日课程",
    lessonMasteredBanner: "🎉 本课已掌握通关！",
    todayGoalCompleted: "今日学习已达成 🎉",
    startReviewSession: "开始复习任务 ({n} 字待复习)",
    nextLessonComingSoon: "👉 下一课《{title}》即将推出，敬请期待！",
    draftTasksTitle: "关卡 {n} 自编练习卡片"
  },
  "en": {
    morning: "Good Morning",
    weekN: "Week {n}",
    menu: "Menu",
    brandTitle: "TongXuan Chinese",
    brandEnSubtitle: "TONGXUAN",
    levelProgressSub: "🎯 Level {n} · In Progress 🔄",
    pinkyPactChip: "🤙 Pinky Promise: {current}/{total} days",
    myAchievements: "Achievements",
    draftContentNotice: "The levels below are TongXuan-authored samples and are not part of the verified official course.",
    openVerifiedCurriculum: "View official course",
    startValidatedSession: "Start today's lesson",
    sessionProfileMissing: "No official learning profile matches this learner. Ask a parent to add the same name in the curriculum area first.",
    rewardsShop: "Rewards Shop",
    settings: "Settings",
    beginnerChipOn: "Phonetics · ON",
    beginnerChipOff: "Hanzi Only · Reading",
    beginnerModeLabel: "Beginner Phonetic Assist Mode",
    beginnerModeActive: "All characters annotated with Zhuyin/Pinyin",
    beginnerModeInactive: "Character-only reading challenge mode",
    eyeCareMode: "Eye-Care Theme",
    eyeCareDark: "Dark Low-Blue",
    eyeCareLight: "Daylight Mode",
    eyeCareDarkShort: "🌙 On",
    eyeCareLightShort: "☀️ Daylight",
    scriptModeLabel: "Script & Phonetics",
    scriptZhuyin: "Traditional (Zhuyin)",
    scriptPinyin: "Simplified (Pinyin)",
    scriptDual: "Trad + Sim Dual",
    scriptZhuyinShort: "Trad",
    scriptPinyinShort: "Simp",
    scriptDualShort: "Dual",
    displayLangLabel: "Display Language",
    phoneticLabel: "Phonetic Notation",
    phoneticAssistLabel: "Phonetic Assist",
    phoneticShow: "Show Phonetics",
    phoneticHide: "Hide (Reading Challenge)",
    assistZhuyinShort: "Zhuyin",
    assistPinyinShort: "Pinyin",
    assistOffShort: "Hide",
    handModeLabel: "Handedness",
    handRight: "✋ Right",
    handLeft: "🤚 Left",
    stageN: "🚩 Stage {n}",
    sprintDayN: "Day {n}",
    milestoneReview: "Full Review",
    stageQuiz: "Stage Quiz",
    passedStatus: "Passed",
    evalStatus: "Exam",
    voiceGuide: "Voice Guide",
    fullReadAloud: "Full Audio",
    playSentence: "Play",
    repeatSentence: "🎙️ Read Along",
    doneRecording: "⏹️ Done",
    communityFooterText: "☕ TongXuan Chinese is free & open-source · Feedback & suggestions welcome!",
    betaDisclaimerLink: "⚠️ Public Beta · Click to view Disclaimer & Privacy Terms",
    feedbackBtn: "Feedback & Issues",
    sponsorBtn: "Buy Me a Coffee",
    switchUser: "👤 Switch Learner Account",
    parentZone: "Parent Dashboard",
    today: "Today",
    lessonDay: "{day} Lesson",
    lessonDuration: "⏱️ ~{min} mins",
    readAloud: "Read Aloud",
    cardStrokeTitle: "Characters",
    cardVocabTitle: "Vocabulary",
    cardIdiomTitle: "Idioms",
    cardStrokeDualHint: "Stroke order · 5-step interactive character classroom",
    cardStrokeSingleHint: "Tianzige tracing · Tap to enter full character loop",
    cardVocabHint: "Daily essential vocabulary · Listen and speak",
    cardIdiomHint: "Classical idioms and real-life context stories",
    exitClass: "Exit Class",
    step1Title: "🌟 Step 1: Look & Recognize",
    step2Title: "✍️ Step 2: Stroke Order & Tracing",
    step3Title: "📝 Step 3: Silent Dictation Challenge",
    step4Title: "🗣️ Step 4: Meaning, Words & Speaking",
    step5Title: "🎯 Step 5: End-of-Lesson Mini Quiz",
    traceCountLabel: "Remaining",
    traceOnceBtn: "✍️ Done",
    traceCountDone: "🎉 Writing phase complete!",
    dictationHint: "Write from memory! Tap 💡 Hint if stuck.",
    dictationClear: "Clear",
    dictationToggleHint: "Hint",
    dictationSubmit: "Done",
    dictationPassed: "Awesome! Dictation passed!",
    standardSound: "Audio",
    speakBtn: "Voice Test",
    sentencePlay: "Play Story Sentence",
    prevStep: "Back",
    nextStep: "Next",
    finishLessonBtn: "Complete Today's Lesson 🎉",
    rewardClaimReturn: "Claim Rewards & Finish",
    traceHint: "Trace the strokes inside the grid with your finger!",
    traceBothTip: "Trad「{t}」{ts} strokes · Sim「{s}」{ss} strokes",
    traceSameTip: "「{c}」is identical in Trad & Sim, {n} strokes (Radical: {r})",
    speakInstruction: "Read aloud with accurate tone!",
    praiseGood: "Excellent reading! Very accurate pronunciation!",
    chestTitle: "🎁 Sunday Mystery Chests",
    chestSub: "Open chests every Sunday for exciting rewards!",
    normalChestTitle: "📦 Chest 1: Completion Chest",
    normalChestCond: "Pass 6 days this week (no streak required)",
    streakChestTitle: "👑 Chest 2: King Streak Chest",
    streakChestCond: "6-day daily streak earns an extra chest on Sunday!",
    rewardText: "Reward: ⭐ +10 Stars + 🎁 Badge",
    rewardStreakText: "Reward: ⭐ Extra +10 Stars + 👑 King Crown",
    openChest: "🎁 Open Chest",
    openKingChest: "👑 Open King Chest",
    needKeys: "{n} keys remaining",
    needStreak: "{n} days streak remaining",
    chestFooter: "💡 Study diligently every day to take home BOTH chests on Sunday!",
    parentGateTitle: "Parent Security Gate",
    parentGateDesc: "Answer the math question to enter the parent area:",
    parentDashboardTitle: "👨‍👩‍👧 Parent Management Dashboard",
    parentDashboardDesc: "Parent verified. Configure daily workload, textbook, and screen limits:",
    parentPlanLabel: "🎯 Daily Pace & Target Time",
    parentCurriculumLabel: "📚 Official Textbook Curriculum",
    saveSettings: "Save Settings",
    aboutModalTitle: "TongXuan Chinese · About, Roadmap & Terms",
    aboutModalSub: "Tailored for young learners & beginners · A warm, playful, systematic Chinese learning platform",
    tabAbout: "🌟 Philosophy & Features",
    tabRoadmap: "🗺️ Learning Roadmap & Exams",
    tabLegal: "⚖️ Curriculum Attribution",
    tabDisclaimer: "📜 Beta Disclaimer & Privacy",
    aboutFeat1Title: "Adaptive Tianzige Writing Practice",
    aboutFeat1Desc: "Hints fade as each learner progresses, with focused retries when independent writing needs practice.",
    aboutFeat2Title: "Dual Zhuyin & Pinyin Support",
    aboutFeat2Desc: "Supports both Taiwan Zhuyin (Bopomofo) and standard Hanyu Pinyin with instant side-by-side comparison.",
    aboutFeat3Title: "TongXuan-authored course samples",
    aboutFeat3Desc: "Levels and characters on this page are TongXuan-authored samples; see the learning map for the verified official course.",
    aboutFeat4Title: "Child-Safe & Eye-Care Design",
    aboutFeat4Desc: "Free of noisy mobile-game ads and microtransactions, featuring dark low-blue mode to protect eyesight.",
    disclaimerTitle: "📜 Public Beta Disclaimer & Privacy Policy",
    disclaimerPoint1Title: "⚠️ Public Beta & Local Storage Notice:",
    disclaimerPoint1Desc: "This project is currently in public beta. When upgrading or clearing browser cache, local learning progress (coins, stars, mistakes, passes) may be reset. The system does not guarantee permanent data persistence.",
    disclaimerPoint2Title: "🔒 Local-First Architecture & Anonymous Analytics:",
    disclaimerPoint2Desc: "TongXuan adheres strictly to youth privacy standards and collects zero PII (no names, emails, audio uploads, or tracking cookies). We only gather de-identified, aggregated learning milestones (e.g. level completion counts) to improve curriculum quality. All learning records remain 100% in your local browser sandbox.",
    disclaimerPoint3Title: "📚 Educational Tool Non-Guarantee:",
    disclaimerPoint3Desc: "This application is an independent self-study aid and not an accredited academic institution. We make no guarantees regarding learning speed, test scores, or specific examination results.",
    disclaimerPoint4Title: "☕ Open Source & Voluntary Sponsorship:",
    disclaimerPoint4Desc: "The source code is published under the MIT license. Buy Me a Coffee sponsorships are voluntary donations and do not constitute commercial contracts, subscriptions, or dedicated support agreements.",
    disclaimerFooter: "TongXuan Chinese strictly adheres to youth privacy standards · Thank you for testing!",
    officialCurriculumBadge: "Official OCAC Curriculum · Permission Pending",
    curriculumObjectives: "Lesson Objectives",
    practiceTargetsLabel: "Practice Targets",
    domainsLabel: "Learning Domains",
    extraPracticeSectionTitle: "TongXuan Authored Practice Prototype",
    extraPracticeSectionNote: "This section contains prototype practice authored by TongXuan for extra exploration. It is not official OCAC material.",
    listeningDomain: "Listening",
    speakingDomain: "Speaking",
    recognitionDomain: "Recognition",
    phoneticsDomain: "Phonetics",
    pronunciationDomain: "Pronunciation",
    vocabularyDomain: "Vocabulary",
    grammarDomain: "Grammar",
    writingDomain: "Writing",
    readingDomain: "Reading",
    upcomingLessonBadge: "Upcoming lesson",
    upcomingLessonNotice: "Upcoming curriculum lesson · Please complete today's lesson first",
    backToTodayLesson: "Return to Today's Lesson",
    lessonMasteredBanner: "🎉 Lesson Mastered!",
    todayGoalCompleted: "Today's Goal Completed 🎉",
    startReviewSession: "Start Review Task ({n} due)",
    nextLessonComingSoon: "👉 Next lesson 《{title}》 coming soon!",
    draftTasksTitle: "Level {n} Practice Cards"
  },
  "ja": {
    morning: "おはよう",
    weekN: "第 {n} 週",
    menu: "メニュー",
    brandTitle: "桐軒中国語",
    brandEnSubtitle: "TONGXUAN",
    levelProgressSub: "🎯 第 {n} レベル · 挑戦中 🔄",
    pinkyPactChip: "🤙 指切り約束：{current}/{total} 日",
    myAchievements: "実績・バッジ",
    draftContentNotice: "以下のレベルは桐軒が作成したサンプルで、公式教材として検証されていません。",
    openVerifiedCurriculum: "公式コースを見る",
    startValidatedSession: "今日の学習を始める",
    sessionProfileMissing: "この学習者に一致する公式学習プロフィールがありません。保護者の方はコース画面で同じ名前の学習者を追加してください。",
    rewardsShop: "ご褒美ショップ",
    settings: "設定",
    beginnerChipOn: "ふりがな補助 · ON",
    beginnerChipOff: "漢字のみ · 読解",
    beginnerModeLabel: "初心者ふりがなモード",
    beginnerModeActive: "全画面の漢字に注音・ピンインを表示",
    beginnerModeInactive: "漢字のみの読解チャレンジ",
    eyeCareMode: "アイケアモード",
    eyeCareDark: "ダーク・低ブルーライト",
    eyeCareLight: "デイライト",
    eyeCareDarkShort: "🌙 オン",
    eyeCareLightShort: "☀️ デイ",
    scriptModeLabel: "文字と発音表記",
    scriptZhuyin: "繁体字（注音）",
    scriptPinyin: "簡体字（ピンイン）",
    scriptDual: "繁＋簡両方",
    scriptZhuyinShort: "繁体",
    scriptPinyinShort: "簡体",
    scriptDualShort: "繁＋簡",
    displayLangLabel: "表示言語",
    phoneticLabel: "ふりがな・発音表示",
    phoneticAssistLabel: "ふりがな補助",
    phoneticShow: "表示する",
    phoneticHide: "隠す (漢字挑戦)",
    assistZhuyinShort: "注音",
    assistPinyinShort: "ピンイン",
    assistOffShort: "非表示",
    handModeLabel: "利き手切り替え",
    handRight: "✋ 右手",
    handLeft: "🤚 左手",
    stageN: "🚩 第 {n} ステージ",
    sprintDayN: "{n}日目",
    milestoneReview: "総復習",
    stageQuiz: "確認テスト",
    passedStatus: "合格",
    evalStatus: "検定",
    voiceGuide: "音声ガイド",
    fullReadAloud: "全文朗読",
    playSentence: "再生",
    repeatSentence: "🎙️ シャドーイング",
    doneRecording: "⏹️ 完了",
    communityFooterText: "☕ 桐軒中国語は無料のオープンソースです · ご意見やフィードバックを歓迎します！",
    betaDisclaimerLink: "⚠️ 現在オープンベータ版です · 免責事項とプライバシーポリシーを見る",
    feedbackBtn: "ご意見・問題報告",
    sponsorBtn: "開発者にコーヒーを奢る",
    switchUser: "👤 学習者を切り替え",
    parentZone: "保護者ダッシュボード",
    today: "今日",
    lessonDay: "{day} レッスン",
    lessonDuration: "⏱️ 毎日約 {min} 分（{count} 文字）",
    readAloud: "本文朗読",
    cardStrokeTitle: "生字・読み書き",
    cardVocabTitle: "単語・語彙",
    cardIdiomTitle: "成語・お話",
    cardStrokeDualHint: "田字格筆順 · 5ステップ全循環学習",
    cardStrokeSingleHint: "田字格なぞり書き · タップして練習",
    cardVocabHint: "生活頻出語彙 · 発音を聞いて練習",
    cardIdiomHint: "成語の由来とお話の理解",
    exitClass: "教室を出る",
    step1Title: "🌟 ステップ 1: 見て覚える",
    step2Title: "✍️ ステップ 2: なぞり書き練習",
    step3Title: "📝 ステップ 3: 記憶書き取りテスト",
    step4Title: "🗣️ ステップ 4: 語彙と発音テスト",
    step5Title: "🎯 ステップ 5: レッスン確認テスト",
    traceCountLabel: "残り回数",
    traceOnceBtn: "✍️ 完了",
    traceCountDone: "🎉 書字段階を完了！",
    dictationHint: "記憶を頼りに書こう！困ったら 💡 ヒント。",
    dictationClear: "消去",
    dictationToggleHint: "ヒント",
    dictationSubmit: "提出",
    dictationPassed: "素晴らしい！書き取り成功！",
    standardSound: "音声",
    speakBtn: "録音テスト",
    sentencePlay: "例文を再生",
    prevStep: "前へ",
    nextStep: "次へ",
    finishLessonBtn: "今日のレッスン完了 🎉",
    rewardClaimReturn: "報酬を受け取って戻る",
    traceHint: "指で田字格の漢字をなぞってみましょう！",
    traceBothTip: "繁体字「{t}」{ts}画 · 簡体字「{s}」{ss}画",
    traceSameTip: "「{c}」は繁簡同形（{n}画、部首：{r}）",
    speakInstruction: "声に出して標準発音を練習しましょう！",
    praiseGood: "素晴らしい発音です！",
    chestTitle: "🎁 日曜日の宝箱",
    chestSub: "毎週日曜日に宝箱を開けてプレゼントをもらおう！",
    normalChestTitle: "📦 宝箱 1：通関宝箱",
    normalChestCond: "今週6日間クリアで開放",
    streakChestTitle: "👑 宝箱 2：連続王者宝箱",
    streakChestCond: "6日間連続学習で追加宝箱！",
    rewardText: "報酬：⭐ +10 星 + 🎁 バッジ",
    rewardStreakText: "報酬：⭐ 追加 +10 星 + 👑 王冠",
    openChest: "🎁 宝箱を開ける",
    openKingChest: "👑 王者宝箱を開ける",
    needKeys: "あと {n} 本の鍵",
    needStreak: "あと {n} 日連続",
    chestFooter: "💡 毎日学習して、日曜日に2つの宝箱をゲットしよう！",
    parentGateTitle: "保護者専用ゲート",
    parentGateDesc: "計算問題に答えて保護者設定へ：",
    parentDashboardTitle: "👨‍👩‍👧 保護者管理ダッシュボード",
    parentDashboardDesc: "毎日の学習量・教材を設定：",
    parentPlanLabel: "🎯 毎日の学習時間",
    parentCurriculumLabel: "📚 教材コース",
    saveSettings: "設定を保存",
    aboutModalTitle: "桐軒中国語 · 概要・ロードマップ・利用規約",
    aboutModalSub: "海外の子供や初心者のために作られた、体系的で楽しい中国語学習プラットフォーム",
    tabAbout: "🌟 理念と特徴",
    tabRoadmap: "🗺️ ロードマップと検定目標",
    tabLegal: "⚖️ 教材の出典と著作権",
    tabDisclaimer: "📜 ベータ版免責事項",
    aboutFeat1Title: "段階式ヒントの田字格書写練習",
    aboutFeat1Desc: "学習者の書写状況に合わせてヒントを減らし、必要な字だけ再練習します。",
    aboutFeat2Title: "注音・ピンインのデュアル対応",
    aboutFeat2Desc: "台湾注音（ボポモフォ）と国際漢語ピンインの両方に対応し、繁体・簡体をシームレスに学習。",
    aboutFeat3Title: "桐軒作成の学習サンプル",
    aboutFeat3Desc: "このページのレベルと漢字は桐軒が作成したサンプルです。検証済みの公式コースは学習マップをご覧ください。",
    aboutFeat4Title: "子供に安心な学習環境",
    aboutFeat4Desc: "広告や過度なゲーム要素を排除し、目に優しいダークモードで視力を保護します。",
    disclaimerTitle: "📜 オープンベータ版 免責事項とプライバシーポリシー",
    disclaimerPoint1Title: "⚠️ ベータ版とデータ保存について：",
    disclaimerPoint1Desc: "本プロジェクトは現在公開ベータテスト中です。アップデートやブラウザのキャッシュ削除により、端末内の学習データがリセットされる場合があります。データの永久保存は保証されません。",
    disclaimerPoint2Title: "🔒 完全ローカル処理と個人情報：",
    disclaimerPoint2Desc: "本システムはLocal-Firstアーキテクチャを採用し、サーバー側でユーザーデータを保持しません。すべてのデータはお使いの端末のブラウザ内のみに保存されます。",
    disclaimerPoint3Title: "📚 自主学習ツールとしての免責：",
    disclaimerPoint3Desc: "本システムは個人の自主学習補助ツールです。公式の教育機関ではなく、学習進度や試験結果を保証するものではありません。",
    disclaimerPoint4Title: "☕ オープンソースとサポート：",
    disclaimerPoint4Desc: "本コードはMITライセンスで公開されています。Buy Me a Coffeeでのご支援は自発的な寄付であり、商用契約や個別サポートを保証するものではありません。",
    disclaimerFooter: "桐軒中国語は青少年のプライバシーと安全を遵守します · ご理解とご協力に感謝いたします",
    officialCurriculumBadge: "公式カリキュラム · 許諾審査中",
    curriculumObjectives: "学習目標",
    practiceTargetsLabel: "練習のポイント",
    domainsLabel: "学習分野",
    extraPracticeSectionTitle: "TongXuan 独自作成の体験練習",
    extraPracticeSectionNote: "このセクションは拡張練習用の試作教材です。公式教材ではありません。",
    listeningDomain: "リスニング",
    speakingDomain: "スピーキング",
    recognitionDomain: "漢字認識",
    phoneticsDomain: "発音記号",
    pronunciationDomain: "発音",
    vocabularyDomain: "語彙",
    grammarDomain: "文法",
    writingDomain: "書き取り",
    readingDomain: "読解",
    upcomingLessonBadge: "次のレッスン",
    upcomingLessonNotice: "今後のカリキュラム内容です · まず今日のレッスンを完了してください",
    backToTodayLesson: "今日のレッスンに戻る",
    lessonMasteredBanner: "🎉 このレッスンは習得完了です！",
    todayGoalCompleted: "今日の学習目標達成 🎉",
    startReviewSession: "復習タスクを開始 ({n} 件)",
    nextLessonComingSoon: "👉 次のレッスン《{title}》近日公開予定！",
    draftTasksTitle: "レベル {n} 練習カード"
  },
  "ko": {
    morning: "좋은 아침",
    weekN: "{n} 주차",
    menu: "메뉴",
    brandTitle: "통쉬안 중국어",
    brandEnSubtitle: "TONGXUAN",
    levelProgressSub: "🎯 레벨 {n} · 도전 중 🔄",
    pinkyPactChip: "🤙 새끼손가락 약속：{current}/{total} 일",
    myAchievements: "나의 업적",
    draftContentNotice: "아래 단계는 TongXuan 자체 제작 예시이며 공식 교재로 검증되지 않았습니다.",
    openVerifiedCurriculum: "공식 교육과정 보기",
    startValidatedSession: "오늘 학습 시작",
    sessionProfileMissing: "이 학습자와 일치하는 공식 학습 프로필이 없습니다. 보호자가 교육과정 화면에서 같은 이름의 학습자를 먼저 추가해 주세요.",
    rewardsShop: "보상 상점",
    settings: "설정",
    beginnerChipOn: "초보자 발음 표기 · 켜짐",
    beginnerChipOff: "순수 한자 · 읽기",
    beginnerModeLabel: "초보자 발음 보조 모드 (전체 한자 표기)",
    beginnerModeActive: "화면의 모든 한자에 주음/병음 발음 표기",
    beginnerModeInactive: "순수 한자 읽기 도전 모드",
    eyeCareMode: "눈 보호 모드",
    eyeCareDark: "다크 모드",
    eyeCareLight: "라이트 모드",
    eyeCareDarkShort: "🌙 켜짐",
    eyeCareLightShort: "☀️ 낮",
    scriptModeLabel: "글자 및 발음 표기",
    scriptZhuyin: "번체자 (주음)",
    scriptPinyin: "간체자 (병음)",
    scriptDual: "번체+간체 듀얼",
    scriptZhuyinShort: "번체",
    scriptPinyinShort: "간체",
    scriptDualShort: "번+간",
    displayLangLabel: "표시 언어",
    phoneticLabel: "발음 표기 표시",
    phoneticAssistLabel: "독서 발음 보조",
    phoneticShow: "표기 켜기",
    phoneticHide: "숨기기 (한자 도전)",
    assistZhuyinShort: "주음",
    assistPinyinShort: "병음",
    assistOffShort: "숨김",
    handModeLabel: "주로 쓰는 손",
    handRight: "✋ 오른손",
    handLeft: "🤚 왼손",
    stageN: "🚩 제 {n} 단계",
    sprintDayN: "{n}일차",
    milestoneReview: "전체 복습",
    stageQuiz: "종합 퀴즈",
    passedStatus: "합격",
    evalStatus: "검정",
    voiceGuide: "음성 가이드",
    fullReadAloud: "전체 듣기",
    playSentence: "문장 듣기",
    repeatSentence: "🎙️ 따라 읽기",
    doneRecording: "⏹️ 완료",
    communityFooterText: "☕ 통쉬안 중국어는 무료 오픈소스 프로젝트입니다 · 피드백과 제안을 환영합니다!",
    betaDisclaimerLink: "⚠️ 현재 공개 베타 버전입니다 · 면책 조항 및 개인정보 보호정책 보기",
    feedbackBtn: "문제 및 피드백 보고",
    sponsorBtn: "개발자에게 커피 한 잔",
    switchUser: "👤 학습자 계정 전환",
    parentZone: "학부모 관리 설정",
    today: "오늘",
    lessonDay: "{day} 수업",
    lessonDuration: "⏱️ 하루 약 {min}분 ({count}개 핵심 한자)",
    readAloud: "본문 듣기",
    cardStrokeTitle: "한자 · 읽고 쓰기",
    cardVocabTitle: "어휘 · 문장",
    cardIdiomTitle: "고사성어",
    cardStrokeDualHint: "십자 격자 획순 · 5단계 한자 완성 루프",
    cardStrokeSingleHint: "격자 획순 쓰기 연습 · 탭하여 시작",
    cardVocabHint: "일상 필수 어휘 · 발음 듣기",
    cardIdiomHint: "고사성어 이야기와 실생활 활용",
    exitClass: "수업 종료",
    step1Title: "🌟 1단계: 글자 모양 익히기",
    step2Title: "✍️ 2단계: 획순 따라 쓰기",
    step3Title: "📝 3단계: 기억 쓰기 도전",
    step4Title: "🗣️ 4단계: 단어 및 발음 연습",
    step5Title: "🎯 5단계: 수업 확인 퀴즈",
    traceCountLabel: "남은 횟수",
    traceOnceBtn: "✍️ 완료",
    traceCountDone: "🎉 쓰기 단계를 완료했어요!",
    dictationHint: "기억해서 써보세요! 막히면 💡 힌트.",
    dictationClear: "지우기",
    dictationToggleHint: "힌트",
    dictationSubmit: "제출",
    dictationPassed: "훌륭해요! 쓰기 성공!",
    standardSound: "발음",
    speakBtn: "음성 평가",
    sentencePlay: "문장 듣기",
    prevStep: "이전",
    nextStep: "다음",
    finishLessonBtn: "오늘의 학습 완료 🎉",
    rewardClaimReturn: "보상 받고 돌아가기",
    traceHint: "손가락으로 격자 안의 획을 따라 써보세요!",
    traceBothTip: "번체「{t}」{ts}획 · 간체「{s}」{ss}획",
    traceSameTip: "「{c}」은(는) 번체/간체 동일 ({n}획, 부수: {r})",
    speakInstruction: "큰 소리로 표준 성조를 따라 해보세요!",
    praiseGood: "참 잘했어요! 발음이 정확합니다!",
    chestTitle: "🎁 일요일 비밀 보물상자",
    chestSub: "매주 일요일 상자를 열어 보상을 받으세요!",
    normalChestTitle: "📦 상자 1: 주간 완주 상자",
    normalChestCond: "이번 주 6일 학습 시 오픈",
    streakChestTitle: "👑 상자 2: 연속 출석 왕 상자",
    streakChestCond: "6일 연속 학습 시 추가 오픈!",
    rewardText: "보상: ⭐ +10 별 + 🎁 배지",
    rewardStreakText: "보상: ⭐ 추가 +10 별 + 👑 왕관",
    openChest: "🎁 상자 열기",
    openKingChest: "👑 왕 보물상자 열기",
    needKeys: "열쇠 {n}개 남음",
    needStreak: "{n}일 연속 출석 남음",
    chestFooter: "💡 매일 성실히 학습하면 일요일에 상자 2개를 모두 열 수 있어요!",
    parentGateTitle: "학부모 인증 잠금",
    parentGateDesc: "산수 문제를 풀어 학부모 화면으로 이동하세요:",
    parentDashboardTitle: "👨‍👩‍👧 학부모 학습 관리 센터",
    parentDashboardDesc: "하루 학습량, 교재 및 사용 시간 설정:",
    parentPlanLabel: "🎯 일일 학습 목표",
    parentCurriculumLabel: "📚 공식 교재 과정",
    saveSettings: "설정 저장",
    aboutModalTitle: "통쉬안 중국어 · 소개, 로드맵 및 이용약관",
    aboutModalSub: "해외 어린이 및 초보자를 위한 따뜻하고 체계적인 중국어 학습 플랫폼",
    tabAbout: "🌟 교육 철학 및 특징",
    tabRoadmap: "🗺️ 학습 로드맵 및 검정 목표",
    tabLegal: "⚖️ 교재 출처 및 저작권",
    tabDisclaimer: "📜 베타 면책 조항 및 개인정보",
    aboutFeat1Title: "단계별 힌트 격자 쓰기 연습",
    aboutFeat1Desc: "학습 상태에 따라 힌트를 줄이고, 필요한 글자만 골라 다시 연습합니다.",
    aboutFeat2Title: "주음부호 및 한어병음 듀얼 지원",
    aboutFeat2Desc: "대만 주음부호와 표준 한어병음을 모두 지원하여 번체/간체를 손쉽게 학습합니다.",
    aboutFeat3Title: "TongXuan 자체 제작 학습 예시",
    aboutFeat3Desc: "이 페이지의 단계와 한자는 TongXuan 자체 제작 예시입니다. 검증된 공식 과정은 학습 지도에서 확인하세요.",
    aboutFeat4Title: "어린이 안심 및 시력 보호",
    aboutFeat4Desc: "상업적 광고나 과도한 게임 요소를 배제하고, 눈에 편안한 다크 모드를 지원합니다.",
    disclaimerTitle: "📜 공개 베타 (Beta) 면책 조항 및 개인정보 보호정책",
    disclaimerPoint1Title: "⚠️ 공개 베타 버전 및 데이터 보존 안내:",
    disclaimerPoint1Desc: "본 프로젝트는 공개 베타 테스트 중입니다. 시스템 업데이트나 브라우저 캐시 삭제 시 기기에 저장된 학습 데이터(코인, 별, 오답, 티켓 등)가 초기화될 수 있습니다.",
    disclaimerPoint2Title: "🔒 완전 로컬 처리 및 비호스팅 정책:",
    disclaimerPoint2Desc: "본 시스템은 Local-First 프런트엔드 구조로 서버에 사용자 데이터베이스를 운영하지 않습니다. 모든 데이터는 100% 현재 브라우저 샌드박스에만 보관됩니다.",
    disclaimerPoint3Title: "📚 비공식 학습 도구 및 성과 비보증:",
    disclaimerPoint3Desc: "본 시스템은 개인 자율 학습 보조 도구이며 공식 교육 기관이 아닙니다. 학습 속도나 특정 시험 성적을 보증하지 않습니다.",
    disclaimerPoint4Title: "☕ 오픈소스 및 자발적 후원:",
    disclaimerPoint4Desc: "소스 코드는 MIT 라이선스로 배포됩니다. Buy Me a Coffee를 통한 후원은 자발적 응원이며, 상업적 구독이나 개별 지원 의무를 발생시키지 않습니다.",
    disclaimerFooter: "통쉬안 중국어는 아동 개인정보 보호 규정을 준수합니다 · 테스트에 참여해 주셔서 감사합니다",
    officialCurriculumBadge: "공식 교육과정 · 허가 심사 중",
    curriculumObjectives: "학습 목표",
    practiceTargetsLabel: "핵심 연습 과제",
    domainsLabel: "학습 영역",
    extraPracticeSectionTitle: "TongXuan 자체 제작 연습 예시",
    extraPracticeSectionNote: "이 영역은 TongXuan 초기 시제품 연습이며 공식 교재가 아닙니다.",
    listeningDomain: "듣기",
    speakingDomain: "말하기",
    recognitionDomain: "글자 인식",
    phoneticsDomain: "발음 기호",
    pronunciationDomain: "발음",
    vocabularyDomain: "어휘",
    grammarDomain: "문법",
    writingDomain: "쓰기",
    readingDomain: "읽기",
    upcomingLessonBadge: "다음 수업",
    upcomingLessonNotice: "다음 교육과정 내용입니다 · 오늘의 수업을 먼저 완료해주세요",
    backToTodayLesson: "오늘의 수업으로 돌아가기",
    lessonMasteredBanner: "🎉 이번 수업을 마스터했습니다!",
    todayGoalCompleted: "오늘의 학습 목표 달성 🎉",
    startReviewSession: "복습 시작 ({n}개 대기 중)",
    nextLessonComingSoon: "👉 다음 수업 《{title}》 곧 공개됩니다!",
    draftTasksTitle: "레벨 {n} 연습 카드"
  },
  "es": {
    morning: "Buenos días",
    weekN: "Semana {n}",
    menu: "Menú",
    brandTitle: "TongXuan Chino",
    brandEnSubtitle: "TONGXUAN",
    levelProgressSub: "🎯 Nivel {n} · En progreso 🔄",
    pinkyPactChip: "🤙 Promesa: {current}/{total} días",
    myAchievements: "Logros",
    draftContentNotice: "Los niveles siguientes son ejemplos creados por TongXuan y no forman parte del curso oficial verificado.",
    openVerifiedCurriculum: "Ver curso oficial",
    startValidatedSession: "Empezar la lección de hoy",
    sessionProfileMissing: "No hay un perfil oficial que coincida con este estudiante. Pide a un adulto que lo añada con el mismo nombre en el área de cursos.",
    rewardsShop: "Tienda de Premios",
    settings: "Ajustes",
    beginnerChipOn: "Modo Principiante · ON",
    beginnerChipOff: "Solo Caracteres · ON",
    beginnerModeLabel: "Modo Principiante (Anotación Fonética)",
    beginnerModeActive: "Muestra notación fonética en todos los caracteres",
    beginnerModeInactive: "Modo de lectura de solo caracteres",
    eyeCareMode: "Modo Cuidado Visual",
    eyeCareDark: "Modo Oscuro",
    eyeCareLight: "Modo Día",
    eyeCareDarkShort: "🌙 Activado",
    eyeCareLightShort: "☀️ Día",
    scriptModeLabel: "Modo de Aprendizaje",
    scriptZhuyin: "Tradicional (Zhuyin)",
    scriptPinyin: "Simplificado (Pinyin)",
    scriptDual: "Trad + Simp Dual",
    scriptZhuyinShort: "Trad",
    scriptPinyinShort: "Simp",
    scriptDualShort: "Dual",
    displayLangLabel: "Idioma de Interfaz",
    phoneticLabel: "Notación Fonética",
    phoneticAssistLabel: "Asistencia Fonética",
    phoneticShow: "Mostrar Fonética",
    phoneticHide: "Ocultar (Reto de Caracteres)",
    assistZhuyinShort: "Zhuyin",
    assistPinyinShort: "Pinyin",
    assistOffShort: "Ocultar",
    handModeLabel: "Mano Dominante",
    handRight: "✋ Diestro",
    handLeft: "🤚 Zurdo",
    stageN: "🚩 Etapa {n}",
    sprintDayN: "Día {n}",
    milestoneReview: "Repaso Total",
    stageQuiz: "Cuestionario",
    passedStatus: "Aprobado",
    evalStatus: "Examen",
    voiceGuide: "Guía de Voz",
    fullReadAloud: "Lectura Completa",
    playSentence: "Escuchar",
    repeatSentence: "🎙️ Repetir",
    doneRecording: "⏹️ Listo",
    communityFooterText: "☕ TongXuan Chinese es libre y de código abierto · ¡Agradecemos sus comentarios!",
    betaDisclaimerLink: "⚠️ Versión Beta Pública · Ver Descargo de Responsabilidad y Privacidad",
    feedbackBtn: "Comentarios y Sugerencias",
    sponsorBtn: "Invitar un Café",
    switchUser: "👤 Cambiar de Usuario",
    parentZone: "Panel de Padres",
    today: "Hoy",
    lessonDay: "Lección del {day}",
    lessonDuration: "⏱️ ~{min} min al día ({count} caracteres)",
    readAloud: "Leer Texto",
    cardStrokeTitle: "Caracteres",
    cardVocabTitle: "Vocabulario",
    cardIdiomTitle: "Modismos",
    cardStrokeDualHint: "Cuadrícula · Bucle de 5 pasos para dominar caracteres",
    cardStrokeSingleHint: "Trazado de caracteres · Tocar para practicar",
    cardVocabHint: "Vocabulario común esencial · Escuchar y pronunciar",
    cardIdiomHint: "Cuentos de modismos tradicionales en contexto",
    exitClass: "Salir",
    step1Title: "🌟 Paso 1: Ver y Reconocer",
    step2Title: "✍️ Paso 2: Orden de Trazos y Trazado",
    step3Title: "📝 Paso 3: Reto de Escritura de Memoria",
    step4Title: "🗣️ Paso 4: Significado y Pronunciación",
    step5Title: "🎯 Paso 5: Mini Cuestionario Final",
    traceCountLabel: "Restante",
    traceOnceBtn: "✍️ Listo",
    traceCountDone: "🎉 ¡Fase de escritura completada!",
    dictationHint: "¡Escribe de memoria! Toca 💡 Pista.",
    dictationClear: "Borrar",
    dictationToggleHint: "Pista",
    dictationSubmit: "Comprobar",
    dictationPassed: "¡Excelente! ¡Dictado aprobado!",
    standardSound: "Audio",
    speakBtn: "Voz",
    sentencePlay: "Reproducir Oración",
    prevStep: "Atrás",
    nextStep: "Siguiente",
    finishLessonBtn: "¡Completar Lección de Hoy! 🎉",
    rewardClaimReturn: "Reclamar Recompensas",
    traceHint: "¡Traza los caracteres con tu dedo en la cuadrícula!",
    traceBothTip: "Trad「{t}」{ts} trazos · Simp「{s}」{ss} trazos",
    traceSameTip: "「{c}」es idéntico en Trad/Simp, {n} trazos (Radical: {r})",
    speakInstruction: "¡Lee en voz alta con tono estándar!",
    praiseGood: "¡Excelente pronunciación!",
    chestTitle: "🎁 Cofre Misterioso del Domingo",
    chestSub: "¡Abre cofres cada domingo para obtener recompensas!",
    normalChestTitle: "📦 Cofre 1: Misión Semanal",
    normalChestCond: "Completa 6 días de estudio",
    streakChestTitle: "👑 Cofre 2: Corona de Racha",
    streakChestCond: "¡Racha de 6 días para abrir un cofre extra!",
    rewardText: "Recompensa: ⭐ +10 Estrellas + 🎁 Medalla",
    rewardStreakText: "Recompensa: ⭐ +10 Estrellas extra + 👑 Corona",
    openChest: "🎁 Abrir Cofre",
    openKingChest: "👑 Abrir Cofre Real",
    needKeys: "Faltan {n} llaves",
    needStreak: "Faltan {n} días de racha",
    chestFooter: "💡 ¡Aprende cada día y abre ambos cofres el domingo!",
    parentGateTitle: "Control Parental",
    parentGateDesc: "Resuelve el problema matemático para ingresar:",
    parentDashboardTitle: "👨‍👩‍👧 Panel de Gestión Parental",
    parentDashboardDesc: "Configurar carga diaria, libro de texto y tiempo:",
    parentPlanLabel: "🎯 Meta y Duración Diaria",
    parentCurriculumLabel: "📚 Libro de Texto Oficial",
    saveSettings: "Guardar Cambios",
    aboutModalTitle: "TongXuan Chinese · Acerca de, Hoja de Ruta y Términos",
    aboutModalSub: "Diseñado para niños y principiantes · Una plataforma cálida, lúdica y sistemática para aprender chino",
    tabAbout: "🌟 Filosofía y Características",
    tabRoadmap: "🗺️ Hoja de Ruta y Exámenes",
    tabLegal: "⚖️ Fuentes y Derechos de Autor",
    tabDisclaimer: "📜 Descargo de Responsabilidad Beta",
    aboutFeat1Title: "Práctica adaptativa de trazos Tianzige",
    aboutFeat1Desc: "Las pistas disminuyen según el progreso y se repasan de forma selectiva los caracteres difíciles.",
    aboutFeat2Title: "Soporte Dual Zhuyin y Pinyin",
    aboutFeat2Desc: "Compatible con Zhuyin de Taiwán y Pinyin internacional con comparación instantánea.",
    aboutFeat3Title: "Ejemplos de aprendizaje de TongXuan",
    aboutFeat3Desc: "Los niveles y caracteres de esta página son ejemplos creados por TongXuan. Consulta el mapa de aprendizaje para ver el curso oficial verificado.",
    aboutFeat4Title: "Entorno Seguro y Cuidado Visual",
    aboutFeat4Desc: "Sin anuncios ni compras ruidosas, con modo oscuro de baja emisión azul para cuidar la vista.",
    disclaimerTitle: "📜 Descargo de Responsabilidad Beta Pública y Privacidad",
    disclaimerPoint1Title: "⚠️ Versión Beta Pública y Almacenamiento Local:",
    disclaimerPoint1Desc: "Este proyecto se encuentra en fase beta pública. Al actualizar o borrar la caché del navegador, los datos de aprendizaje locales (monedas, estrellas, errores, vales) pueden restablecerse.",
    disclaimerPoint2Title: "🔒 Arquitectura Local-First y Sin Servidor Central:",
    disclaimerPoint2Desc: "TongXuan opera completamente en el navegador sin base de datos central en servidores. No respaldamos ni recuperamos datos personales.",
    disclaimerPoint3Title: "📚 Herramienta Educativa No Acreditada:",
    disclaimerPoint3Desc: "Esta aplicación es una ayuda de autoaprendizaje independiente y no una institución educativa formal. No garantiza resultados de exámenes específicos.",
    disclaimerPoint4Title: "☕ Código Abierto y Patrocinio Voluntario:",
    disclaimerPoint4Desc: "El código se publica bajo licencia MIT. Los patrocinios en Buy Me a Coffee son donaciones voluntarias y no constituyen contratos comerciales.",
    disclaimerFooter: "TongXuan Chinese protege la privacidad de los menores · ¡Gracias por su apoyo!",
    officialCurriculumBadge: "Currículo oficial · Permiso en trámite",
    curriculumObjectives: "Objetivos de la lección",
    practiceTargetsLabel: "Objetivos de práctica",
    domainsLabel: "Áreas de aprendizaje",
    extraPracticeSectionTitle: "Área de práctica demostrativa TongXuan",
    extraPracticeSectionNote: "Esta sección contiene material de prueba creado por TongXuan para práctica adicional y no es material oficial de OCAC.",
    listeningDomain: "Escucha",
    speakingDomain: "Expresión oral",
    recognitionDomain: "Reconocimiento",
    phoneticsDomain: "Fonética",
    pronunciationDomain: "Pronunciación",
    vocabularyDomain: "Vocabulario",
    grammarDomain: "Gramática",
    writingDomain: "Escritura",
    readingDomain: "Lectura",
    upcomingLessonBadge: "Próxima lección",
    upcomingLessonNotice: "Contenido curricular posterior · Complete primero la lección de hoy",
    backToTodayLesson: "Volver a la lección de hoy",
    lessonMasteredBanner: "🎉 ¡Lección dominada con éxito!",
    todayGoalCompleted: "Objetivo de hoy completado 🎉",
    startReviewSession: "Iniciar repaso ({n} pendientes)",
    nextLessonComingSoon: "👉 ¡Próxima lección 《{title}》 muy pronto!",
    draftTasksTitle: "Tarjetas de práctica del nivel {n}"
  }
};

