import { type ReactNode } from "react";

export interface CharPhonetic {
  zhuyin: string;
  pinyin: string;
}

// Comprehensive Phonetic Dictionary for TongXuan Chinese Curriculum, UI, and Common Words
export const PHONETIC_DICT: Record<string, CharPhonetic> = {
  "一": { zhuyin: "ㄧ", pinyin: "yī" },
  "丈": { zhuyin: "ㄓㄤˋ", pinyin: "zhàng" },
  "三": { zhuyin: "ㄙㄢ", pinyin: "sān" },
  "上": { zhuyin: "ㄕㄤˋ", pinyin: "shàng" },
  "下": { zhuyin: "ㄒㄧㄚˋ", pinyin: "xià" },
  "不": { zhuyin: "ㄅㄨˋ", pinyin: "bù" },
  "与": { zhuyin: "ㄩˇ", pinyin: "yǔ" },
  "专": { zhuyin: "ㄓㄨㄢ", pinyin: "zhuān" },
  "両": { zhuyin: "ㄌㄧㄤˇ", pinyin: "liǎng" },
  "並": { zhuyin: "ㄅㄧㄥˋ", pinyin: "bìng" },
  "个": { zhuyin: "ㄍㄜˋ", pinyin: "gè" },
  "中": { zhuyin: "ㄓㄨㄥ", pinyin: "zhōng" },
  "为": { zhuyin: "ㄨㄟˋ", pinyin: "wèi" },
  "主": { zhuyin: "ㄓㄨˇ", pinyin: "zhǔ" },
  "之": { zhuyin: "ㄓ", pinyin: "zhī" },
  "也": { zhuyin: "ㄧㄝˇ", pinyin: "yě" },
  "习": { zhuyin: "ㄒㄧˊ", pinyin: "xí" },
  "书": { zhuyin: "ㄕㄨ", pinyin: "shū" },
  "了": { zhuyin: "˙ㄌㄜ", pinyin: "le" },
  "事": { zhuyin: "ㄕˋ", pinyin: "shì" },
  "二": { zhuyin: "ㄦˋ", pinyin: "èr" },
  "云": { zhuyin: "ㄩㄣˊ", pinyin: "yún" },
  "互": { zhuyin: "ㄏㄨˋ", pinyin: "hù" },
  "五": { zhuyin: "ㄨˇ", pinyin: "wǔ" },
  "亮": { zhuyin: "ㄌㄧㄤˋ", pinyin: "liàng" },
  "人": { zhuyin: "ㄖㄣˊ", pinyin: "rén" },
  "今": { zhuyin: "ㄐㄧㄣ", pinyin: "jīn" },
  "介": { zhuyin: "ㄐㄧㄝˋ", pinyin: "jiè" },
  "代": { zhuyin: "ㄉㄞˋ", pinyin: "dài" },
  "以": { zhuyin: "ㄧˇ", pinyin: "yǐ" },
  "任": { zhuyin: "ㄖㄣˋ", pinyin: "rèn" },
  "份": { zhuyin: "ㄈㄣˋ", pinyin: "fèn" },
  "会": { zhuyin: "ㄏㄨㄟˋ", pinyin: "huì" },
  "位": { zhuyin: "ㄨㄟˋ", pinyin: "wèi" },
  "低": { zhuyin: "ㄉㄧ", pinyin: "dī" },
  "体": { zhuyin: "ㄊㄧˇ", pinyin: "tǐ" },
  "作": { zhuyin: "ㄗㄨㄛˋ", pinyin: "zuò" },
  "使": { zhuyin: "ㄕˇ", pinyin: "shǐ" },
  "來": { zhuyin: "ㄌㄞˊ", pinyin: "lái" },
  "例": { zhuyin: "ㄌㄧˋ", pinyin: "lì" },
  "供": { zhuyin: "ㄍㄨㄥ", pinyin: "gōng" },
  "侨": { zhuyin: "ㄑㄧㄠˊ", pinyin: "qiáo" },
  "保": { zhuyin: "ㄅㄠˇ", pinyin: "bǎo" },
  "個": { zhuyin: "ㄍㄜ˙", pinyin: "ge" },
  "們": { zhuyin: "˙ㄇㄣ", pinyin: "men" },
  "倒": { zhuyin: "ㄉㄠˇ", pinyin: "dǎo" },
  "候": { zhuyin: "ㄏㄡˋ", pinyin: "hòu" },
  "偉": { zhuyin: "ㄨㄟˇ", pinyin: "wěi" },
  "像": { zhuyin: "ㄒㄧㄤˋ", pinyin: "xiàng" },
  "僑": { zhuyin: "ㄑㄧㄠˊ", pinyin: "qiáo" },
  "優": { zhuyin: "ㄧㄡ", pinyin: "yōu" },
  "儲": { zhuyin: "ㄔㄨˊ", pinyin: "chú" },
  "儿": { zhuyin: "ㄦˊ", pinyin: "ér" },
  "充": { zhuyin: "ㄔㄨㄥ", pinyin: "chōng" },
  "光": { zhuyin: "ㄍㄨㄤ", pinyin: "guāng" },
  "兒": { zhuyin: "ㄦˊ", pinyin: "ér" },
  "入": { zhuyin: "ㄖㄨˋ", pinyin: "rù" },
  "內": { zhuyin: "ㄋㄟˋ", pinyin: "nèi" },
  "全": { zhuyin: "ㄑㄩㄢˊ", pinyin: "quán" },
  "兩": { zhuyin: "ㄌㄧㄤˇ", pinyin: "liǎng" },
  "六": { zhuyin: "ㄌㄧㄡˋ", pinyin: "liù" },
  "共": { zhuyin: "ㄍㄨㄥˋ", pinyin: "gòng" },
  "关": { zhuyin: "ㄍㄨㄢ", pinyin: "guān" },
  "典": { zhuyin: "ㄉㄧㄢˇ", pinyin: "diǎn" },
  "内": { zhuyin: "ㄋㄟˋ", pinyin: "nèi" },
  "冊": { zhuyin: "ㄘㄜˋ", pinyin: "cè" },
  "册": { zhuyin: "ㄘㄜˋ", pinyin: "cè" },
  "再": { zhuyin: "ㄗㄞˋ", pinyin: "zài" },
  "写": { zhuyin: "ㄒㄧㄝˇ", pinyin: "xiě" },
  "冠": { zhuyin: "ㄍㄨㄢ", pinyin: "guān" },
  "冬": { zhuyin: "ㄉㄨㄥ", pinyin: "dōng" },
  "冷": { zhuyin: "ㄌㄥˇ", pinyin: "lěng" },
  "准": { zhuyin: "ㄓㄨㄣˇ", pinyin: "zhǔn" },
  "出": { zhuyin: "ㄔㄨ", pinyin: "chū" },
  "击": { zhuyin: "ㄐㄧˊ", pinyin: "jí" },
  "分": { zhuyin: "ㄈㄣ", pinyin: "fēn" },
  "切": { zhuyin: "ㄑㄧㄝ", pinyin: "qiē" },
  "初": { zhuyin: "ㄔㄨ", pinyin: "chū" },
  "利": { zhuyin: "ㄌㄧˋ", pinyin: "lì" },
  "到": { zhuyin: "ㄉㄠˋ", pinyin: "dào" },
  "制": { zhuyin: "ㄓˋ", pinyin: "zhì" },
  "刺": { zhuyin: "ㄘˋ", pinyin: "cì" },
  "前": { zhuyin: "ㄑㄧㄢˊ", pinyin: "qián" },
  "劃": { zhuyin: "ㄏㄨㄚˋ", pinyin: "huà" },
  "力": { zhuyin: "ㄌㄧˋ", pinyin: "lì" },
  "功": { zhuyin: "ㄍㄨㄥ", pinyin: "gōng" },
  "加": { zhuyin: "ㄐㄧㄚ", pinyin: "jiā" },
  "励": { zhuyin: "ㄌㄧˋ", pinyin: "lì" },
  "勃": { zhuyin: "ㄅㄛˊ", pinyin: "bó" },
  "動": { zhuyin: "ㄉㄨㄥˋ", pinyin: "dòng" },
  "務": { zhuyin: "ㄨˋ", pinyin: "wù" },
  "勝": { zhuyin: "ㄕㄥˋ", pinyin: "shèng" },
  "勞": { zhuyin: "ㄌㄠˊ", pinyin: "láo" },
  "勢": { zhuyin: "ㄕˋ", pinyin: "shì" },
  "勤": { zhuyin: "ㄑㄧㄣˊ", pinyin: "qín" },
  "勵": { zhuyin: "ㄌㄧˋ", pinyin: "lì" },
  "勾": { zhuyin: "ㄍㄡ", pinyin: "gōu" },
  "化": { zhuyin: "ㄏㄨㄚˋ", pinyin: "huà" },
  "匙": { zhuyin: "˙ㄔ", pinyin: "shi" },
  "匯": { zhuyin: "ㄏㄨㄟˋ", pinyin: "huì" },
  "区": { zhuyin: "ㄑㄩ", pinyin: "qū" },
  "區": { zhuyin: "ㄑㄩ", pinyin: "qū" },
  "升": { zhuyin: "ㄕㄥ", pinyin: "shēng" },
  "午": { zhuyin: "ㄨˇ", pinyin: "wǔ" },
  "单": { zhuyin: "ㄉㄢ", pinyin: "dān" },
  "卡": { zhuyin: "ㄎㄚˇ", pinyin: "kǎ" },
  "即": { zhuyin: "ㄐㄧˊ", pinyin: "jí" },
  "原": { zhuyin: "ㄩㄢˊ", pinyin: "yuán" },
  "去": { zhuyin: "ㄑㄩˋ", pinyin: "qù" },
  "及": { zhuyin: "ㄐㄧˊ", pinyin: "jí" },
  "友": { zhuyin: "ㄧㄡˇ", pinyin: "yǒu" },
  "双": { zhuyin: "ㄕㄨㄤ", pinyin: "shuāng" },
  "反": { zhuyin: "ㄈㄢˇ", pinyin: "fǎn" },
  "发": { zhuyin: "ㄈㄚ", pinyin: "fā" },
  "取": { zhuyin: "ㄑㄩˇ", pinyin: "qǔ" },
  "受": { zhuyin: "ㄕㄡˋ", pinyin: "shòu" },
  "叢": { zhuyin: "ㄘㄨㄥˊ", pinyin: "cóng" },
  "口": { zhuyin: "ㄎㄡˇ", pinyin: "kǒu" },
  "句": { zhuyin: "ㄐㄩˋ", pinyin: "jù" },
  "可": { zhuyin: "ㄎㄜˇ", pinyin: "kě" },
  "台": { zhuyin: "ㄊㄞˊ", pinyin: "tái" },
  "右": { zhuyin: "ㄧㄡˋ", pinyin: "yòu" },
  "号": { zhuyin: "ㄏㄠˋ", pinyin: "hào" },
  "吃": { zhuyin: "ㄔ", pinyin: "chī" },
  "各": { zhuyin: "ㄍㄜˋ", pinyin: "gè" },
  "合": { zhuyin: "ㄏㄜˊ", pinyin: "hé" },
  "同": { zhuyin: "ㄊㄨㄥˊ", pinyin: "tóng" },
  "名": { zhuyin: "ㄇㄧㄥˊ", pinyin: "míng" },
  "后": { zhuyin: "ㄏㄡˋ", pinyin: "hòu" },
  "向": { zhuyin: "ㄒㄧㄤˋ", pinyin: "xiàng" },
  "吧": { zhuyin: "˙ㄅㄚ", pinyin: "ba" },
  "听": { zhuyin: "ㄊㄧㄥ", pinyin: "tīng" },
  "启": { zhuyin: "ㄑㄧˇ", pinyin: "qǐ" },
  "吹": { zhuyin: "ㄔㄨㄟ", pinyin: "chuī" },
  "告": { zhuyin: "ㄍㄠˋ", pinyin: "gào" },
  "周": { zhuyin: "ㄓㄡ", pinyin: "zhōu" },
  "味": { zhuyin: "ㄨㄟˋ", pinyin: "wèi" },
  "和": { zhuyin: "ㄏㄜˊ", pinyin: "hé" },
  "唱": { zhuyin: "ㄔㄤˋ", pinyin: "chàng" },
  "問": { zhuyin: "ㄨㄣˋ", pinyin: "wèn" },
  "啟": { zhuyin: "ㄑㄧˇ", pinyin: "qǐ" },
  "喔": { zhuyin: "ㄛ", pinyin: "ō" },
  "喜": { zhuyin: "ㄒㄧˇ", pinyin: "xǐ" },
  "單": { zhuyin: "ㄉㄢ", pinyin: "dān" },
  "喻": { zhuyin: "ㄩˋ", pinyin: "yù" },
  "四": { zhuyin: "ㄙˋ", pinyin: "sì" },
  "回": { zhuyin: "ㄏㄨㄟˊ", pinyin: "huí" },
  "國": { zhuyin: "ㄍㄨㄛˊ", pinyin: "guó" },
  "圓": { zhuyin: "ㄩㄢˊ", pinyin: "yuán" },
  "圖": { zhuyin: "ㄊㄨˊ", pinyin: "tú" },
  "團": { zhuyin: "ㄊㄨㄢˊ", pinyin: "tuán" },
  "土": { zhuyin: "ㄊㄨˇ", pinyin: "tǔ" },
  "在": { zhuyin: "ㄗㄞˋ", pinyin: "zài" },
  "地": { zhuyin: "ㄉㄧˋ", pinyin: "dì" },
  "坡": { zhuyin: "ㄆㄛ", pinyin: "pō" },
  "域": { zhuyin: "ㄩˋ", pinyin: "yù" },
  "基": { zhuyin: "ㄐㄧ", pinyin: "jī" },
  "報": { zhuyin: "ㄅㄠˋ", pinyin: "bào" },
  "境": { zhuyin: "ㄐㄧㄥˋ", pinyin: "jìng" },
  "增": { zhuyin: "ㄗㄥ", pinyin: "zēng" },
  "壯": { zhuyin: "ㄓㄨㄤˋ", pinyin: "zhuàng" },
  "声": { zhuyin: "ㄕㄥ", pinyin: "shēng" },
  "夏": { zhuyin: "ㄒㄧㄚˋ", pinyin: "xià" },
  "外": { zhuyin: "ㄨㄞˋ", pinyin: "wài" },
  "多": { zhuyin: "ㄉㄨㄛ", pinyin: "duō" },
  "夜": { zhuyin: "ㄧㄝˋ", pinyin: "yè" },
  "大": { zhuyin: "ㄉㄚˋ", pinyin: "dà" },
  "天": { zhuyin: "ㄊㄧㄢ", pinyin: "tiān" },
  "太": { zhuyin: "ㄊㄞˋ", pinyin: "tài" },
  "夫": { zhuyin: "ㄈㄨ", pinyin: "fū" },
  "奇": { zhuyin: "ㄑㄧˊ", pinyin: "qí" },
  "奔": { zhuyin: "ㄅㄣ", pinyin: "bēn" },
  "奖": { zhuyin: "ㄐㄧㄤˇ", pinyin: "jiǎng" },
  "好": { zhuyin: "ㄏㄠˇ", pinyin: "hǎo" },
  "如": { zhuyin: "ㄖㄨˊ", pinyin: "rú" },
  "妙": { zhuyin: "ㄇㄧㄠˋ", pinyin: "miào" },
  "始": { zhuyin: "ㄕˇ", pinyin: "shǐ" },
  "姓": { zhuyin: "ㄒㄧㄥˋ", pinyin: "xìng" },
  "委": { zhuyin: "ㄨㄟˇ", pinyin: "wěi" },
  "媚": { zhuyin: "ㄇㄟˋ", pinyin: "mèi" },
  "嫩": { zhuyin: "ㄋㄣˋ", pinyin: "nèn" },
  "子": { zhuyin: "ㄗˇ", pinyin: "zǐ" },
  "字": { zhuyin: "ㄗˋ", pinyin: "zì" },
  "存": { zhuyin: "ㄘㄨㄣˊ", pinyin: "cún" },
  "学": { zhuyin: "ㄒㄩㄝˊ", pinyin: "xué" },
  "學": { zhuyin: "ㄒㄩㄝˊ", pinyin: "xué" },
  "安": { zhuyin: "ㄢ", pinyin: "ān" },
  "完": { zhuyin: "ㄨㄢˊ", pinyin: "wán" },
  "定": { zhuyin: "ㄉㄧㄥˋ", pinyin: "dìng" },
  "宜": { zhuyin: "ㄧˊ", pinyin: "yí" },
  "宝": { zhuyin: "ㄅㄠˇ", pinyin: "bǎo" },
  "宣": { zhuyin: "ㄒㄩㄢ", pinyin: "xuān" },
  "室": { zhuyin: "ㄕˋ", pinyin: "shì" },
  "家": { zhuyin: "ㄐㄧㄚ", pinyin: "jiā" },
  "容": { zhuyin: "ㄖㄨㄥˊ", pinyin: "róng" },
  "密": { zhuyin: "ㄇㄧˋ", pinyin: "mì" },
  "富": { zhuyin: "ㄈㄨˋ", pinyin: "fù" },
  "寒": { zhuyin: "ㄏㄢˊ", pinyin: "hán" },
  "寫": { zhuyin: "ㄒㄧㄝˇ", pinyin: "xiě" },
  "寬": { zhuyin: "ㄎㄨㄢ", pinyin: "kuān" },
  "寶": { zhuyin: "ㄅㄠˇ", pinyin: "bǎo" },
  "对": { zhuyin: "ㄉㄨㄟˋ", pinyin: "duì" },
  "対": { zhuyin: "ㄉㄨㄟˋ", pinyin: "duì" },
  "専": { zhuyin: "ㄓㄨㄢ", pinyin: "zhuān" },
  "專": { zhuyin: "ㄓㄨㄢ", pinyin: "zhuān" },
  "對": { zhuyin: "ㄉㄨㄟˋ", pinyin: "duì" },
  "小": { zhuyin: "ㄒㄧㄠˇ", pinyin: "xiǎo" },
  "就": { zhuyin: "ㄐㄧㄡˋ", pinyin: "jiù" },
  "居": { zhuyin: "ㄐㄩ", pinyin: "jū" },
  "展": { zhuyin: "ㄓㄢˇ", pinyin: "zhǎn" },
  "山": { zhuyin: "ㄕㄢ", pinyin: "shān" },
  "川": { zhuyin: "ㄔㄨㄢ", pinyin: "chuān" },
  "左": { zhuyin: "ㄗㄨㄛˇ", pinyin: "zuǒ" },
  "差": { zhuyin: "ㄔㄚ", pinyin: "chā" },
  "已": { zhuyin: "ㄧˇ", pinyin: "yǐ" },
  "帳": { zhuyin: "ㄓㄤˋ", pinyin: "zhàng" },
  "常": { zhuyin: "ㄔㄤˊ", pinyin: "cháng" },
  "幅": { zhuyin: "ㄈㄨˊ", pinyin: "fú" },
  "幕": { zhuyin: "ㄇㄨˋ", pinyin: "mù" },
  "平": { zhuyin: "ㄆㄧㄥˊ", pinyin: "píng" },
  "年": { zhuyin: "ㄋㄧㄢˊ", pinyin: "nián" },
  "并": { zhuyin: "ㄅㄧㄥˋ", pinyin: "bìng" },
  "幼": { zhuyin: "ㄧㄡˋ", pinyin: "yòu" },
  "度": { zhuyin: "ㄉㄨˋ", pinyin: "dù" },
  "座": { zhuyin: "ㄗㄨㄛˋ", pinyin: "zuò" },
  "庫": { zhuyin: "ㄎㄨˋ", pinyin: "kù" },
  "庭": { zhuyin: "ㄊㄧㄥˊ", pinyin: "tíng" },
  "廣": { zhuyin: "ㄍㄨㄤˇ", pinyin: "guǎng" },
  "开": { zhuyin: "ㄎㄞ", pinyin: "kāi" },
  "式": { zhuyin: "ㄕˋ", pinyin: "shì" },
  "強": { zhuyin: "ㄑㄧㄤˊ", pinyin: "qiáng" },
  "彈": { zhuyin: "ㄉㄢˋ", pinyin: "dàn" },
  "彎": { zhuyin: "ㄨㄢ", pinyin: "wān" },
  "录": { zhuyin: "ㄌㄨˋ", pinyin: "lù" },
  "形": { zhuyin: "ㄒㄧㄥˊ", pinyin: "xíng" },
  "很": { zhuyin: "ㄏㄣˇ", pinyin: "hěn" },
  "後": { zhuyin: "ㄏㄡˋ", pinyin: "hòu" },
  "得": { zhuyin: "ㄉㄜˊ", pinyin: "dé" },
  "從": { zhuyin: "ㄘㄨㄥˊ", pinyin: "cóng" },
  "循": { zhuyin: "ㄒㄩㄣˊ", pinyin: "xún" },
  "微": { zhuyin: "ㄨㄟ", pinyin: "wēi" },
  "徽": { zhuyin: "ㄏㄨㄟ", pinyin: "huī" },
  "心": { zhuyin: "ㄒㄧㄣ", pinyin: "xīn" },
  "忙": { zhuyin: "ㄇㄤˊ", pinyin: "máng" },
  "応": { zhuyin: "ㄧㄥˋ", pinyin: "yìng" },
  "快": { zhuyin: "ㄎㄨㄞˋ", pinyin: "kuài" },
  "忽": { zhuyin: "ㄏㄨ", pinyin: "hū" },
  "恭": { zhuyin: "ㄍㄨㄥ", pinyin: "gōng" },
  "情": { zhuyin: "ㄑㄧㄥˊ", pinyin: "qíng" },
  "意": { zhuyin: "ㄧˋ", pinyin: "yì" },
  "愛": { zhuyin: "ㄞˋ", pinyin: "ài" },
  "應": { zhuyin: "ㄧㄥˋ", pinyin: "yìng" },
  "成": { zhuyin: "ㄔㄥˊ", pinyin: "chéng" },
  "我": { zhuyin: "ㄨㄛˇ", pinyin: "wǒ" },
  "或": { zhuyin: "ㄏㄨㄛˋ", pinyin: "huò" },
  "战": { zhuyin: "ㄓㄢˋ", pinyin: "zhàn" },
  "戦": { zhuyin: "ㄓㄢˋ", pinyin: "zhàn" },
  "戰": { zhuyin: "ㄓㄢˋ", pinyin: "zhàn" },
  "戻": { zhuyin: "ㄌㄟˋ", pinyin: "lèi" },
  "手": { zhuyin: "ㄕㄡˇ", pinyin: "shǒu" },
  "打": { zhuyin: "ㄉㄚˇ", pinyin: "dǎ" },
  "把": { zhuyin: "ㄅㄚˇ", pinyin: "bǎ" },
  "护": { zhuyin: "ㄏㄨˋ", pinyin: "hù" },
  "抱": { zhuyin: "ㄅㄠˋ", pinyin: "bào" },
  "拂": { zhuyin: "ㄈㄨˊ", pinyin: "fú" },
  "拓": { zhuyin: "ㄊㄨㄛˋ", pinyin: "tuò" },
  "拼": { zhuyin: "ㄆㄧㄣ", pinyin: "pīn" },
  "持": { zhuyin: "ㄔˊ", pinyin: "chí" },
  "指": { zhuyin: "ㄓˇ", pinyin: "zhǐ" },
  "挑": { zhuyin: "ㄊㄧㄠˇ", pinyin: "tiǎo" },
  "换": { zhuyin: "ㄏㄨㄢˋ", pinyin: "huàn" },
  "掌": { zhuyin: "ㄓㄤˇ", pinyin: "zhǎng" },
  "排": { zhuyin: "ㄆㄞˊ", pinyin: "pái" },
  "探": { zhuyin: "ㄊㄢˋ", pinyin: "tàn" },
  "控": { zhuyin: "ㄎㄨㄥˋ", pinyin: "kòng" },
  "推": { zhuyin: "ㄊㄨㄟ", pinyin: "tuī" },
  "描": { zhuyin: "ㄇㄧㄠˊ", pinyin: "miáo" },
  "提": { zhuyin: "ㄊㄧˊ", pinyin: "tí" },
  "揚": { zhuyin: "ㄧㄤˊ", pinyin: "yáng" },
  "換": { zhuyin: "ㄏㄨㄢˋ", pinyin: "huàn" },
  "握": { zhuyin: "ㄨㄛˋ", pinyin: "wò" },
  "播": { zhuyin: "ㄅㄛ", pinyin: "bō" },
  "擇": { zhuyin: "ㄗㄜˊ", pinyin: "zé" },
  "擊": { zhuyin: "ㄐㄧˊ", pinyin: "jí" },
  "支": { zhuyin: "ㄓ", pinyin: "zhī" },
  "收": { zhuyin: "ㄕㄡ", pinyin: "shōu" },
  "放": { zhuyin: "ㄈㄤˋ", pinyin: "fàng" },
  "故": { zhuyin: "ㄍㄨˋ", pinyin: "gù" },
  "教": { zhuyin: "ㄐㄧㄠˋ", pinyin: "jiào" },
  "散": { zhuyin: "ㄙㄢˋ", pinyin: "sàn" },
  "整": { zhuyin: "ㄓㄥˇ", pinyin: "zhěng" },
  "數": { zhuyin: "ㄕㄨˋ", pinyin: "shù" },
  "文": { zhuyin: "ㄨㄣˊ", pinyin: "wén" },
  "新": { zhuyin: "ㄒㄧㄣ", pinyin: "xīn" },
  "方": { zhuyin: "ㄈㄤ", pinyin: "fāng" },
  "旅": { zhuyin: "ㄌㄩˇ", pinyin: "lǚ" },
  "日": { zhuyin: "ㄖˋ", pinyin: "rì" },
  "早": { zhuyin: "ㄗㄠˇ", pinyin: "zǎo" },
  "时": { zhuyin: "ㄕˊ", pinyin: "shí" },
  "旺": { zhuyin: "ㄨㄤˋ", pinyin: "wàng" },
  "昆": { zhuyin: "ㄎㄨㄣ", pinyin: "kūn" },
  "明": { zhuyin: "ㄇㄧㄥˊ", pinyin: "míng" },
  "星": { zhuyin: "ㄒㄧㄥ", pinyin: "xīng" },
  "春": { zhuyin: "ㄔㄨㄣ", pinyin: "chūn" },
  "是": { zhuyin: "ㄕˋ", pinyin: "shì" },
  "显": { zhuyin: "ㄒㄧㄢˇ", pinyin: "xiǎn" },
  "時": { zhuyin: "ㄕˊ", pinyin: "shí" },
  "晚": { zhuyin: "ㄨㄢˇ", pinyin: "wǎn" },
  "晨": { zhuyin: "ㄔㄣˊ", pinyin: "chén" },
  "景": { zhuyin: "ㄐㄧㄥˇ", pinyin: "jǐng" },
  "晴": { zhuyin: "ㄑㄧㄥˊ", pinyin: "qíng" },
  "晶": { zhuyin: "ㄐㄧㄥ", pinyin: "jīng" },
  "暖": { zhuyin: "ㄋㄨㄢˇ", pinyin: "nuǎn" },
  "曜": { zhuyin: "ㄧㄠˋ", pinyin: "yào" },
  "書": { zhuyin: "ㄕㄨ", pinyin: "shū" },
  "替": { zhuyin: "ㄊㄧˋ", pinyin: "tì" },
  "會": { zhuyin: "ㄏㄨㄟˋ", pinyin: "huì" },
  "月": { zhuyin: "ㄩㄝˋ", pinyin: "yuè" },
  "有": { zhuyin: "ㄧㄡˇ", pinyin: "yǒu" },
  "朋": { zhuyin: "ㄆㄥˊ", pinyin: "péng" },
  "朗": { zhuyin: "ㄌㄤˇ", pinyin: "lǎng" },
  "望": { zhuyin: "ㄨㄤˋ", pinyin: "wàng" },
  "木": { zhuyin: "ㄇㄨˋ", pinyin: "mù" },
  "本": { zhuyin: "ㄅㄣˇ", pinyin: "běn" },
  "术": { zhuyin: "ㄕㄨˋ", pinyin: "shù" },
  "朵": { zhuyin: "ㄉㄨㄛˇ", pinyin: "duǒ" },
  "材": { zhuyin: "ㄘㄞˊ", pinyin: "cái" },
  "東": { zhuyin: "ㄉㄨㄥ", pinyin: "dōng" },
  "析": { zhuyin: "ㄒㄧ", pinyin: "xī" },
  "林": { zhuyin: "ㄌㄧㄣˊ", pinyin: "lín" },
  "柔": { zhuyin: "ㄖㄡˊ", pinyin: "róu" },
  "标": { zhuyin: "ㄅㄧㄠ", pinyin: "biāo" },
  "校": { zhuyin: "ㄒㄧㄠˋ", pinyin: "xiào" },
  "格": { zhuyin: "ㄍㄜˊ", pinyin: "gé" },
  "案": { zhuyin: "ㄢˋ", pinyin: "àn" },
  "條": { zhuyin: "ㄊㄧㄠˊ", pinyin: "tiáo" },
  "棒": { zhuyin: "ㄅㄤˋ", pinyin: "bàng" },
  "森": { zhuyin: "ㄙㄣ", pinyin: "sēn" },
  "棵": { zhuyin: "ㄎㄜ", pinyin: "kē" },
  "構": { zhuyin: "ㄍㄡˋ", pinyin: "gòu" },
  "樂": { zhuyin: "ㄌㄜˋ", pinyin: "lè" },
  "標": { zhuyin: "ㄅㄧㄠ", pinyin: "biāo" },
  "模": { zhuyin: "ㄇㄛˊ", pinyin: "mó" },
  "樣": { zhuyin: "ㄧㄤˋ", pinyin: "yàng" },
  "樹": { zhuyin: "ㄕㄨˋ", pinyin: "shù" },
  "機": { zhuyin: "ㄐㄧ", pinyin: "jī" },
  "次": { zhuyin: "ㄘˋ", pinyin: "cì" },
  "歌": { zhuyin: "ㄍㄜ", pinyin: "gē" },
  "歡": { zhuyin: "ㄏㄨㄢ", pinyin: "huān" },
  "正": { zhuyin: "ㄓㄥˋ", pinyin: "zhèng" },
  "此": { zhuyin: "ㄘˇ", pinyin: "cǐ" },
  "步": { zhuyin: "ㄅㄨˋ", pinyin: "bù" },
  "歲": { zhuyin: "ㄙㄨㄟˋ", pinyin: "suì" },
  "段": { zhuyin: "ㄉㄨㄢˋ", pinyin: "duàn" },
  "毎": { zhuyin: "ㄇㄟˇ", pinyin: "měi" },
  "每": { zhuyin: "ㄇㄟˇ", pinyin: "měi" },
  "比": { zhuyin: "ㄅㄧˇ", pinyin: "bǐ" },
  "氣": { zhuyin: "ㄑㄧˋ", pinyin: "qì" },
  "水": { zhuyin: "ㄕㄨㄟˇ", pinyin: "shuǐ" },
  "汉": { zhuyin: "ㄏㄢˋ", pinyin: "hàn" },
  "江": { zhuyin: "ㄐㄧㄤ", pinyin: "jiāng" },
  "沃": { zhuyin: "ㄨㄛˋ", pinyin: "wò" },
  "沉": { zhuyin: "ㄔㄣˊ", pinyin: "chén" },
  "河": { zhuyin: "ㄏㄜˊ", pinyin: "hé" },
  "泊": { zhuyin: "ㄅㄛˊ", pinyin: "bó" },
  "泡": { zhuyin: "ㄆㄠˋ", pinyin: "pào" },
  "波": { zhuyin: "ㄅㄛ", pinyin: "bō" },
  "泥": { zhuyin: "ㄋㄧˊ", pinyin: "ní" },
  "注": { zhuyin: "ㄓㄨˋ", pinyin: "zhù" },
  "活": { zhuyin: "ㄏㄨㄛˊ", pinyin: "huó" },
  "流": { zhuyin: "ㄌㄧㄡˊ", pinyin: "liú" },
  "测": { zhuyin: "ㄘㄜˋ", pinyin: "cè" },
  "浪": { zhuyin: "ㄌㄤˋ", pinyin: "làng" },
  "海": { zhuyin: "ㄏㄞˇ", pinyin: "hǎi" },
  "浸": { zhuyin: "ㄐㄧㄣˋ", pinyin: "jìn" },
  "深": { zhuyin: "ㄕㄣ", pinyin: "shēn" },
  "清": { zhuyin: "ㄑㄧㄥ", pinyin: "qīng" },
  "測": { zhuyin: "ㄘㄜˋ", pinyin: "cè" },
  "游": { zhuyin: "ㄧㄡˊ", pinyin: "yóu" },
  "湖": { zhuyin: "ㄏㄨˊ", pinyin: "hú" },
  "準": { zhuyin: "ㄓㄨㄣˇ", pinyin: "zhǔn" },
  "溪": { zhuyin: "ㄒㄧ", pinyin: "xī" },
  "溫": { zhuyin: "ㄨㄣ", pinyin: "wēn" },
  "滋": { zhuyin: "ㄗ", pinyin: "zī" },
  "滑": { zhuyin: "ㄏㄨㄚˊ", pinyin: "huá" },
  "滿": { zhuyin: "ㄇㄢˇ", pinyin: "mǎn" },
  "漢": { zhuyin: "ㄏㄢˋ", pinyin: "hàn" },
  "潔": { zhuyin: "ㄐㄧㄝˊ", pinyin: "jié" },
  "潤": { zhuyin: "ㄖㄨㄣˋ", pinyin: "rùn" },
  "澈": { zhuyin: "ㄔㄜˋ", pinyin: "chè" },
  "灑": { zhuyin: "ㄙㄚˇ", pinyin: "sǎ" },
  "灣": { zhuyin: "ㄨㄢ", pinyin: "wān" },
  "火": { zhuyin: "ㄏㄨㄛˇ", pinyin: "huǒ" },
  "炎": { zhuyin: "ㄧㄢˊ", pinyin: "yán" },
  "点": { zhuyin: "ㄉㄧㄢˇ", pinyin: "diǎn" },
  "為": { zhuyin: "ㄨㄟˋ", pinyin: "wèi" },
  "無": { zhuyin: "ㄨˊ", pinyin: "wú" },
  "焰": { zhuyin: "ㄧㄢˋ", pinyin: "yàn" },
  "然": { zhuyin: "ㄖㄢˊ", pinyin: "rán" },
  "煦": { zhuyin: "ㄒㄩˋ", pinyin: "xù" },
  "照": { zhuyin: "ㄓㄠˋ", pinyin: "zhào" },
  "熱": { zhuyin: "ㄖㄜˋ", pinyin: "rè" },
  "燈": { zhuyin: "ㄉㄥ", pinyin: "dēng" },
  "營": { zhuyin: "ㄧㄥˊ", pinyin: "yíng" },
  "片": { zhuyin: "ㄆㄧㄢˋ", pinyin: "piàn" },
  "版": { zhuyin: "ㄅㄢˇ", pinyin: "bǎn" },
  "牛": { zhuyin: "ㄋㄧㄡˊ", pinyin: "niú" },
  "物": { zhuyin: "ㄨˋ", pinyin: "wù" },
  "狀": { zhuyin: "ㄓㄨㄤˋ", pinyin: "zhuàng" },
  "獎": { zhuyin: "ㄐㄧㄤˇ", pinyin: "jiǎng" },
  "獨": { zhuyin: "ㄉㄨˊ", pinyin: "dú" },
  "獲": { zhuyin: "ㄏㄨㄛˋ", pinyin: "huò" },
  "王": { zhuyin: "ㄨㄤˊ", pinyin: "wáng" },
  "班": { zhuyin: "ㄅㄢ", pinyin: "bān" },
  "理": { zhuyin: "ㄌㄧˇ", pinyin: "lǐ" },
  "環": { zhuyin: "ㄏㄨㄢˊ", pinyin: "huán" },
  "生": { zhuyin: "ㄕㄥ", pinyin: "shēng" },
  "用": { zhuyin: "ㄩㄥˋ", pinyin: "yòng" },
  "田": { zhuyin: "ㄊㄧㄢˊ", pinyin: "tián" },
  "电": { zhuyin: "ㄉㄧㄢˋ", pinyin: "diàn" },
  "画": { zhuyin: "ㄏㄨㄚˋ", pinyin: "huà" },
  "界": { zhuyin: "ㄐㄧㄝˋ", pinyin: "jiè" },
  "畫": { zhuyin: "ㄏㄨㄚˋ", pinyin: "huà" },
  "當": { zhuyin: "ㄉㄤ", pinyin: "dāng" },
  "発": { zhuyin: "ㄈㄚ", pinyin: "fā" },
  "登": { zhuyin: "ㄉㄥ", pinyin: "dēng" },
  "發": { zhuyin: "ㄈㄚ", pinyin: "fā" },
  "白": { zhuyin: "ㄅㄞˊ", pinyin: "bái" },
  "的": { zhuyin: "˙ㄉㄜ", pinyin: "de" },
  "皇": { zhuyin: "ㄏㄨㄤˊ", pinyin: "huáng" },
  "盒": { zhuyin: "ㄏㄜˊ", pinyin: "hé" },
  "盛": { zhuyin: "ㄕㄥˋ", pinyin: "shèng" },
  "目": { zhuyin: "ㄇㄨˋ", pinyin: "mù" },
  "相": { zhuyin: "ㄒㄧㄤ", pinyin: "xiāng" },
  "看": { zhuyin: "ㄎㄢˋ", pinyin: "kàn" },
  "真": { zhuyin: "ㄓㄣ", pinyin: "zhēn" },
  "眨": { zhuyin: "ㄓㄚˇ", pinyin: "zhǎ" },
  "眼": { zhuyin: "ㄧㄢˇ", pinyin: "yǎn" },
  "着": { zhuyin: "˙ㄓㄜ", pinyin: "zhe" },
  "睛": { zhuyin: "ㄐㄧㄥ", pinyin: "jīng" },
  "石": { zhuyin: "ㄕˊ", pinyin: "shí" },
  "破": { zhuyin: "ㄆㄛˋ", pinyin: "pò" },
  "碌": { zhuyin: "ㄌㄨˋ", pinyin: "lù" },
  "確": { zhuyin: "ㄑㄩㄝˋ", pinyin: "què" },
  "礎": { zhuyin: "ㄔㄨˇ", pinyin: "chǔ" },
  "示": { zhuyin: "ㄕˋ", pinyin: "shì" },
  "礼": { zhuyin: "ㄌㄧˇ", pinyin: "lǐ" },
  "社": { zhuyin: "ㄕㄜˋ", pinyin: "shè" },
  "祖": { zhuyin: "ㄗㄨˇ", pinyin: "zǔ" },
  "神": { zhuyin: "ㄕㄣˊ", pinyin: "shén" },
  "禮": { zhuyin: "ㄌㄧˇ", pinyin: "lǐ" },
  "禾": { zhuyin: "ㄏㄜˊ", pinyin: "hé" },
  "秀": { zhuyin: "ㄒㄧㄡˋ", pinyin: "xiù" },
  "秘": { zhuyin: "ㄇㄧˋ", pinyin: "mì" },
  "程": { zhuyin: "ㄔㄥˊ", pinyin: "chéng" },
  "種": { zhuyin: "ㄓㄨㄥˇ", pinyin: "zhǒng" },
  "稻": { zhuyin: "ㄉㄠˋ", pinyin: "dào" },
  "積": { zhuyin: "ㄐㄧ", pinyin: "jī" },
  "空": { zhuyin: "ㄎㄨㄥ", pinyin: "kōng" },
  "穿": { zhuyin: "ㄔㄨㄢ", pinyin: "chuān" },
  "窗": { zhuyin: "ㄔㄨㄤ", pinyin: "chuāng" },
  "章": { zhuyin: "ㄓㄤ", pinyin: "zhāng" },
  "童": { zhuyin: "ㄊㄨㄥˊ", pinyin: "tóng" },
  "笑": { zhuyin: "ㄒㄧㄠˋ", pinyin: "xiào" },
  "笔": { zhuyin: "ㄅㄧˇ", pinyin: "bǐ" },
  "符": { zhuyin: "ㄈㄨˊ", pinyin: "fú" },
  "第": { zhuyin: "ㄉㄧˋ", pinyin: "dì" },
  "筆": { zhuyin: "ㄅㄧˇ", pinyin: "bǐ" },
  "答": { zhuyin: "ㄉㄚˊ", pinyin: "dá" },
  "简": { zhuyin: "ㄐㄧㄢˇ", pinyin: "jiǎn" },
  "算": { zhuyin: "ㄙㄨㄢˋ", pinyin: "suàn" },
  "管": { zhuyin: "ㄍㄨㄢˇ", pinyin: "guǎn" },
  "箱": { zhuyin: "ㄒㄧㄤ", pinyin: "xiāng" },
  "篇": { zhuyin: "ㄆㄧㄢ", pinyin: "piān" },
  "篝": { zhuyin: "ㄍㄡ", pinyin: "gōu" },
  "簡": { zhuyin: "ㄐㄧㄢˇ", pinyin: "jiǎn" },
  "精": { zhuyin: "ㄐㄧㄥ", pinyin: "jīng" },
  "約": { zhuyin: "ㄩㄝ", pinyin: "yuē" },
  "紅": { zhuyin: "ㄏㄨㄥˊ", pinyin: "hóng" },
  "純": { zhuyin: "ㄔㄨㄣˊ", pinyin: "chún" },
  "級": { zhuyin: "ㄐㄧˊ", pinyin: "jí" },
  "紛": { zhuyin: "ㄈㄣ", pinyin: "fēn" },
  "素": { zhuyin: "ㄙㄨˋ", pinyin: "sù" },
  "索": { zhuyin: "ㄙㄨㄛˇ", pinyin: "suǒ" },
  "累": { zhuyin: "ㄌㄟˇ", pinyin: "lěi" },
  "細": { zhuyin: "ㄒㄧˋ", pinyin: "xì" },
  "結": { zhuyin: "ㄐㄧㄝˊ", pinyin: "jié" },
  "統": { zhuyin: "ㄊㄨㄥˇ", pinyin: "tǒng" },
  "続": { zhuyin: "ㄒㄩˋ", pinyin: "xù" },
  "綠": { zhuyin: "ㄌㄩˋ", pinyin: "lǜ" },
  "維": { zhuyin: "ㄨㄟˊ", pinyin: "wéi" },
  "網": { zhuyin: "ㄨㄤˇ", pinyin: "wǎng" },
  "綿": { zhuyin: "ㄇㄧㄢˊ", pinyin: "mián" },
  "線": { zhuyin: "ㄒㄧㄢˋ", pinyin: "xiàn" },
  "練": { zhuyin: "ㄌㄧㄢˋ", pinyin: "liàn" },
  "緻": { zhuyin: "ㄓˋ", pinyin: "zhì" },
  "總": { zhuyin: "ㄗㄨㄥˇ", pinyin: "zǒng" },
  "繁": { zhuyin: "ㄈㄢˊ", pinyin: "fán" },
  "續": { zhuyin: "ㄒㄩˋ", pinyin: "xù" },
  "红": { zhuyin: "ㄏㄨㄥˊ", pinyin: "hóng" },
  "约": { zhuyin: "ㄩㄝ", pinyin: "yuē" },
  "线": { zhuyin: "ㄒㄧㄢˋ", pinyin: "xiàn" },
  "练": { zhuyin: "ㄌㄧㄢˋ", pinyin: "liàn" },
  "续": { zhuyin: "ㄒㄩˋ", pinyin: "xù" },
  "置": { zhuyin: "ㄓˋ", pinyin: "zhì" },
  "羊": { zhuyin: "ㄧㄤˊ", pinyin: "yáng" },
  "美": { zhuyin: "ㄇㄟˇ", pinyin: "měi" },
  "義": { zhuyin: "ㄧˋ", pinyin: "yì" },
  "習": { zhuyin: "ㄒㄧˊ", pinyin: "xí" },
  "翔": { zhuyin: "ㄒㄧㄤˊ", pinyin: "xiáng" },
  "翠": { zhuyin: "ㄘㄨㄟˋ", pinyin: "cuì" },
  "老": { zhuyin: "ㄌㄠˇ", pinyin: "lǎo" },
  "者": { zhuyin: "ㄓㄜˇ", pinyin: "zhě" },
  "耕": { zhuyin: "ㄍㄥ", pinyin: "gēng" },
  "聆": { zhuyin: "ㄌㄧㄥˊ", pinyin: "líng" },
  "聞": { zhuyin: "ㄨㄣˊ", pinyin: "wén" },
  "聲": { zhuyin: "ㄕㄥ", pinyin: "shēng" },
  "聽": { zhuyin: "ㄊㄧㄥ", pinyin: "tīng" },
  "肥": { zhuyin: "ㄈㄟˊ", pinyin: "féi" },
  "能": { zhuyin: "ㄋㄥˊ", pinyin: "néng" },
  "自": { zhuyin: "ㄗˋ", pinyin: "zì" },
  "臺": { zhuyin: "ㄊㄞˊ", pinyin: "tái" },
  "與": { zhuyin: "ㄩˇ", pinyin: "yǔ" },
  "船": { zhuyin: "ㄔㄨㄢˊ", pinyin: "chuán" },
  "色": { zhuyin: "ㄙㄜˋ", pinyin: "sè" },
  "艸": { zhuyin: "ㄘㄠˇ", pinyin: "cǎo" },
  "芒": { zhuyin: "ㄇㄤˊ", pinyin: "máng" },
  "芬": { zhuyin: "ㄈㄣ", pinyin: "fēn" },
  "花": { zhuyin: "ㄏㄨㄚ", pinyin: "huā" },
  "芳": { zhuyin: "ㄈㄤ", pinyin: "fāng" },
  "苗": { zhuyin: "ㄇㄧㄠˊ", pinyin: "miáo" },
  "茁": { zhuyin: "ㄓㄨㄛˊ", pinyin: "zhuó" },
  "茂": { zhuyin: "ㄇㄠˋ", pinyin: "mào" },
  "草": { zhuyin: "ㄘㄠˇ", pinyin: "cǎo" },
  "菜": { zhuyin: "ㄘㄞˋ", pinyin: "cài" },
  "華": { zhuyin: "ㄏㄨㄚˊ", pinyin: "huá" },
  "萌": { zhuyin: "ㄇㄥˊ", pinyin: "méng" },
  "萬": { zhuyin: "ㄨㄢˋ", pinyin: "wàn" },
  "落": { zhuyin: "ㄌㄨㄛˋ", pinyin: "luò" },
  "著": { zhuyin: "ㄓㄜ˙", pinyin: "zhe" },
  "蒙": { zhuyin: "ㄇㄥˊ", pinyin: "méng" },
  "蒼": { zhuyin: "ㄘㄤ", pinyin: "cāng" },
  "蓝": { zhuyin: "ㄌㄢˊ", pinyin: "lán" },
  "薦": { zhuyin: "ㄐㄧㄢˋ", pinyin: "jiàn" },
  "藍": { zhuyin: "ㄌㄢˊ", pinyin: "lán" },
  "藏": { zhuyin: "ㄘㄤˊ", pinyin: "cáng" },
  "處": { zhuyin: "ㄔㄨˋ", pinyin: "chù" },
  "號": { zhuyin: "ㄏㄠˋ", pinyin: "hào" },
  "虫": { zhuyin: "ㄔㄨㄥˊ", pinyin: "chóng" },
  "螢": { zhuyin: "ㄧㄥˊ", pinyin: "yíng" },
  "蟲": { zhuyin: "ㄔㄨㄥˊ", pinyin: "chóng" },
  "行": { zhuyin: "ㄒㄧㄥˊ", pinyin: "xíng" },
  "術": { zhuyin: "ㄕㄨˋ", pinyin: "shù" },
  "衝": { zhuyin: "ㄔㄨㄥ", pinyin: "chōng" },
  "衡": { zhuyin: "ㄏㄥˊ", pinyin: "héng" },
  "衣": { zhuyin: "ㄧ", pinyin: "yī" },
  "表": { zhuyin: "ㄅㄧㄠˇ", pinyin: "biǎo" },
  "裡": { zhuyin: "ㄌㄧˇ", pinyin: "lǐ" },
  "見": { zhuyin: "ㄐㄧㄢˋ", pinyin: "jiàn" },
  "規": { zhuyin: "ㄍㄨㄟ", pinyin: "guī" },
  "覚": { zhuyin: "ㄐㄩㄝˊ", pinyin: "jué" },
  "解": { zhuyin: "ㄐㄧㄝˇ", pinyin: "jiě" },
  "言": { zhuyin: "ㄧㄢˊ", pinyin: "yán" },
  "訂": { zhuyin: "ㄉㄧㄥˋ", pinyin: "dìng" },
  "計": { zhuyin: "ㄐㄧˋ", pinyin: "jì" },
  "記": { zhuyin: "ㄐㄧˋ", pinyin: "jì" },
  "設": { zhuyin: "ㄕㄜˋ", pinyin: "shè" },
  "許": { zhuyin: "ㄒㄩˇ", pinyin: "xǔ" },
  "評": { zhuyin: "ㄆㄧㄥˊ", pinyin: "píng" },
  "詞": { zhuyin: "ㄘˊ", pinyin: "cí" },
  "話": { zhuyin: "ㄏㄨㄚˋ", pinyin: "huà" },
  "認": { zhuyin: "ㄖㄣˋ", pinyin: "rèn" },
  "語": { zhuyin: "ㄩˇ", pinyin: "yǔ" },
  "說": { zhuyin: "ㄕㄨㄛ", pinyin: "shuō" },
  "読": { zhuyin: "ㄉㄨˊ", pinyin: "dú" },
  "課": { zhuyin: "ㄎㄜˋ", pinyin: "kè" },
  "調": { zhuyin: "ㄉㄧㄠˋ", pinyin: "diào" },
  "請": { zhuyin: "ㄑㄧㄥˇ", pinyin: "qǐng" },
  "證": { zhuyin: "ㄓㄥˋ", pinyin: "zhèng" },
  "識": { zhuyin: "ㄕˊ", pinyin: "shí" },
  "護": { zhuyin: "ㄏㄨˋ", pinyin: "hù" },
  "讀": { zhuyin: "ㄉㄨˊ", pinyin: "dú" },
  "變": { zhuyin: "ㄅㄧㄢˋ", pinyin: "biàn" },
  "认": { zhuyin: "ㄖㄣˋ", pinyin: "rèn" },
  "设": { zhuyin: "ㄕㄜˋ", pinyin: "shè" },
  "证": { zhuyin: "ㄓㄥˋ", pinyin: "zhèng" },
  "评": { zhuyin: "ㄆㄧㄥˊ", pinyin: "píng" },
  "识": { zhuyin: "ㄕˊ", pinyin: "shí" },
  "话": { zhuyin: "ㄏㄨㄚˋ", pinyin: "huà" },
  "语": { zhuyin: "ㄩˇ", pinyin: "yǔ" },
  "说": { zhuyin: "ㄕㄨㄛ", pinyin: "shuō" },
  "请": { zhuyin: "ㄑㄧㄥˇ", pinyin: "qǐng" },
  "读": { zhuyin: "ㄉㄨˊ", pinyin: "dú" },
  "课": { zhuyin: "ㄎㄜˋ", pinyin: "kè" },
  "调": { zhuyin: "ㄉㄧㄠˋ", pinyin: "diào" },
  "豐": { zhuyin: "ㄈㄥ", pinyin: "fēng" },
  "象": { zhuyin: "ㄒㄧㄤˋ", pinyin: "xiàng" },
  "贈": { zhuyin: "ㄗㄥˋ", pinyin: "zèng" },
  "账": { zhuyin: "ㄓㄤˋ", pinyin: "zhàng" },
  "走": { zhuyin: "ㄗㄡˇ", pinyin: "zǒu" },
  "起": { zhuyin: "ㄑㄧˇ", pinyin: "qǐ" },
  "超": { zhuyin: "ㄔㄠ", pinyin: "chāo" },
  "跟": { zhuyin: "ㄍㄣ", pinyin: "gēn" },
  "路": { zhuyin: "ㄌㄨˋ", pinyin: "lù" },
  "身": { zhuyin: "ㄕㄣ", pinyin: "shēn" },
  "軌": { zhuyin: "ㄍㄨㄟˇ", pinyin: "guǐ" },
  "輕": { zhuyin: "ㄑㄧㄥ", pinyin: "qīng" },
  "轟": { zhuyin: "ㄏㄨㄥ", pinyin: "hōng" },
  "轨": { zhuyin: "ㄍㄨㄟˇ", pinyin: "guǐ" },
  "辛": { zhuyin: "ㄒㄧㄣ", pinyin: "xīn" },
  "辰": { zhuyin: "ㄔㄣˊ", pinyin: "chén" },
  "農": { zhuyin: "ㄋㄨㄥˊ", pinyin: "nóng" },
  "迎": { zhuyin: "ㄧㄥˊ", pinyin: "yíng" },
  "近": { zhuyin: "ㄐㄧㄣˋ", pinyin: "jìn" },
  "返": { zhuyin: "ㄈㄢˇ", pinyin: "fǎn" },
  "还": { zhuyin: "ㄏㄞˊ", pinyin: "hái" },
  "进": { zhuyin: "ㄐㄧㄣˋ", pinyin: "jìn" },
  "连": { zhuyin: "ㄌㄧㄢˊ", pinyin: "lián" },
  "迷": { zhuyin: "ㄇㄧˊ", pinyin: "mí" },
  "追": { zhuyin: "ㄓㄨㄟ", pinyin: "zhuī" },
  "退": { zhuyin: "ㄊㄨㄟˋ", pinyin: "tuì" },
  "這": { zhuyin: "ㄓㄜˋ", pinyin: "zhè" },
  "通": { zhuyin: "ㄊㄨㄥ", pinyin: "tōng" },
  "造": { zhuyin: "ㄗㄠˋ", pinyin: "zào" },
  "連": { zhuyin: "ㄌㄧㄢˊ", pinyin: "lián" },
  "週": { zhuyin: "ㄓㄡ", pinyin: "zhōu" },
  "進": { zhuyin: "ㄐㄧㄣˋ", pinyin: "jìn" },
  "遊": { zhuyin: "ㄧㄡˊ", pinyin: "yóu" },
  "過": { zhuyin: "ㄍㄨㄛˋ", pinyin: "guò" },
  "遠": { zhuyin: "ㄩㄢˇ", pinyin: "yuǎn" },
  "選": { zhuyin: "ㄒㄩㄢˇ", pinyin: "xuǎn" },
  "還": { zhuyin: "ㄏㄞˊ", pinyin: "hái" },
  "邊": { zhuyin: "ㄅㄧㄢ", pinyin: "biān" },
  "部": { zhuyin: "ㄅㄨˋ", pinyin: "bù" },
  "配": { zhuyin: "ㄆㄟˋ", pinyin: "pèi" },
  "酬": { zhuyin: "ㄔㄡˊ", pinyin: "chóu" },
  "重": { zhuyin: "ㄓㄨㄥˋ", pinyin: "zhòng" },
  "量": { zhuyin: "ㄌㄧㄤˋ", pinyin: "liàng" },
  "金": { zhuyin: "ㄐㄧㄣ", pinyin: "jīn" },
  "銀": { zhuyin: "ㄧㄣˊ", pinyin: "yín" },
  "錄": { zhuyin: "ㄌㄨˋ", pinyin: "lù" },
  "録": { zhuyin: "ㄌㄨˋ", pinyin: "lù" },
  "鍵": { zhuyin: "ㄐㄧㄢˋ", pinyin: "jiàn" },
  "鎖": { zhuyin: "ㄙㄨㄛˇ", pinyin: "suǒ" },
  "鏡": { zhuyin: "ㄐㄧㄥˋ", pinyin: "jìng" },
  "鐘": { zhuyin: "ㄓㄨㄥ", pinyin: "zhōng" },
  "鑰": { zhuyin: "ㄧㄠˋ", pinyin: "yào" },
  "钟": { zhuyin: "ㄓㄨㄥ", pinyin: "zhōng" },
  "钥": { zhuyin: "ㄧㄠˋ", pinyin: "yào" },
  "锁": { zhuyin: "ㄙㄨㄛˇ", pinyin: "suǒ" },
  "長": { zhuyin: "ㄔㄤˊ", pinyin: "cháng" },
  "长": { zhuyin: "ㄔㄤˊ", pinyin: "cháng" },
  "閃": { zhuyin: "ㄕㄢˇ", pinyin: "shǎn" },
  "閉": { zhuyin: "ㄅㄧˋ", pinyin: "bì" },
  "開": { zhuyin: "ㄎㄞ", pinyin: "kāi" },
  "間": { zhuyin: "ㄐㄧㄢ", pinyin: "jiān" },
  "関": { zhuyin: "ㄍㄨㄢ", pinyin: "guān" },
  "閱": { zhuyin: "ㄩㄝˋ", pinyin: "yuè" },
  "闊": { zhuyin: "ㄎㄨㄛˋ", pinyin: "kuò" },
  "關": { zhuyin: "ㄍㄨㄢ", pinyin: "guān" },
  "问": { zhuyin: "ㄨㄣˋ", pinyin: "wèn" },
  "间": { zhuyin: "ㄐㄧㄢ", pinyin: "jiān" },
  "阅": { zhuyin: "ㄩㄝˋ", pinyin: "yuè" },
  "防": { zhuyin: "ㄈㄤˊ", pinyin: "fáng" },
  "降": { zhuyin: "ㄐㄧㄤˋ", pinyin: "jiàng" },
  "限": { zhuyin: "ㄒㄧㄢˋ", pinyin: "xiàn" },
  "陣": { zhuyin: "ㄓㄣˋ", pinyin: "zhèn" },
  "陽": { zhuyin: "ㄧㄤˊ", pinyin: "yáng" },
  "隆": { zhuyin: "ㄌㄨㄥˊ", pinyin: "lóng" },
  "階": { zhuyin: "ㄐㄧㄝ", pinyin: "jiē" },
  "隐": { zhuyin: "ㄧㄣˇ", pinyin: "yǐn" },
  "際": { zhuyin: "ㄐㄧˋ", pinyin: "jì" },
  "隠": { zhuyin: "ㄧㄣˇ", pinyin: "yǐn" },
  "隱": { zhuyin: "ㄧㄣˇ", pinyin: "yǐn" },
  "隻": { zhuyin: "ㄓ", pinyin: "zhī" },
  "雄": { zhuyin: "ㄒㄧㄨㄥˊ", pinyin: "xióng" },
  "集": { zhuyin: "ㄐㄧˊ", pinyin: "jí" },
  "雙": { zhuyin: "ㄕㄨㄤ", pinyin: "shuāng" },
  "雨": { zhuyin: "ㄩˇ", pinyin: "yǔ" },
  "雪": { zhuyin: "ㄒㄩㄝˇ", pinyin: "xuě" },
  "雲": { zhuyin: "ㄩㄣˊ", pinyin: "yún" },
  "雷": { zhuyin: "ㄌㄟˊ", pinyin: "léi" },
  "電": { zhuyin: "ㄉㄧㄢˋ", pinyin: "diàn" },
  "需": { zhuyin: "ㄒㄩ", pinyin: "xū" },
  "露": { zhuyin: "ㄌㄨˋ", pinyin: "lù" },
  "青": { zhuyin: "ㄑㄧㄥ", pinyin: "qīng" },
  "靜": { zhuyin: "ㄐㄧㄥˋ", pinyin: "jìng" },
  "非": { zhuyin: "ㄈㄟ", pinyin: "fēi" },
  "面": { zhuyin: "ㄇㄧㄢˋ", pinyin: "miàn" },
  "音": { zhuyin: "ㄧㄣ", pinyin: "yīn" },
  "響": { zhuyin: "ㄒㄧㄤˇ", pinyin: "xiǎng" },
  "頂": { zhuyin: "ㄉㄧㄥˇ", pinyin: "dǐng" },
  "順": { zhuyin: "ㄕㄨㄣˋ", pinyin: "shùn" },
  "預": { zhuyin: "ㄩˋ", pinyin: "yù" },
  "領": { zhuyin: "ㄌㄧㄥˇ", pinyin: "lǐng" },
  "頭": { zhuyin: "ㄊㄡˊ", pinyin: "tóu" },
  "顆": { zhuyin: "ㄎㄜ", pinyin: "kē" },
  "題": { zhuyin: "ㄊㄧˊ", pinyin: "tí" },
  "額": { zhuyin: "ㄜˊ", pinyin: "é" },
  "顯": { zhuyin: "ㄒㄧㄢˇ", pinyin: "xiǎn" },
  "顺": { zhuyin: "ㄕㄨㄣˋ", pinyin: "shùn" },
  "领": { zhuyin: "ㄌㄧㄥˇ", pinyin: "lǐng" },
  "题": { zhuyin: "ㄊㄧˊ", pinyin: "tí" },
  "额": { zhuyin: "ㄜˊ", pinyin: "é" },
  "風": { zhuyin: "ㄈㄥ", pinyin: "fēng" },
  "飄": { zhuyin: "ㄆㄧㄠ", pinyin: "piāo" },
  "风": { zhuyin: "ㄈㄥ", pinyin: "fēng" },
  "飛": { zhuyin: "ㄈㄟ", pinyin: "fēi" },
  "養": { zhuyin: "ㄧㄤˇ", pinyin: "yǎng" },
  "饋": { zhuyin: "ㄎㄨㄟˋ", pinyin: "kuì" },
  "首": { zhuyin: "ㄕㄡˇ", pinyin: "shǒu" },
  "香": { zhuyin: "ㄒㄧㄤ", pinyin: "xiāng" },
  "馬": { zhuyin: "ㄇㄚˇ", pinyin: "mǎ" },
  "馳": { zhuyin: "ㄔˊ", pinyin: "chí" },
  "駿": { zhuyin: "ㄐㄩㄣˋ", pinyin: "jùn" },
  "驗": { zhuyin: "ㄧㄢˋ", pinyin: "yàn" },
  "马": { zhuyin: "ㄇㄚˇ", pinyin: "mǎ" },
  "验": { zhuyin: "ㄧㄢˋ", pinyin: "yàn" },
  "體": { zhuyin: "ㄊㄧˇ", pinyin: "tǐ" },
  "高": { zhuyin: "ㄍㄠ", pinyin: "gāo" },
  "魚": { zhuyin: "ㄩˊ", pinyin: "yú" },
  "鱼": { zhuyin: "ㄩˊ", pinyin: "yú" },
  "鳥": { zhuyin: "ㄋㄧㄠˇ", pinyin: "niǎo" },
  "鳴": { zhuyin: "ㄇㄧㄥˊ", pinyin: "míng" },
  "鸟": { zhuyin: "ㄋㄧㄠˇ", pinyin: "niǎo" },
  "麗": { zhuyin: "ㄌㄧˋ", pinyin: "lì" },
  "黃": { zhuyin: "ㄏㄨㄤˊ", pinyin: "huáng" },
  "黑": { zhuyin: "ㄏㄟ", pinyin: "hēi" },
  "點": { zhuyin: "ㄉㄧㄢˇ", pinyin: "diǎn" },
  "齊": { zhuyin: "ㄑㄧˊ", pinyin: "qí" },
  // Common beginner characters
  "爸": { zhuyin: "ㄅㄚˋ", pinyin: "bà" },
  "媽": { zhuyin: "ㄇㄚ", pinyin: "mā" },
  "妈": { zhuyin: "ㄇㄚ", pinyin: "mā" },
  "哥": { zhuyin: "ㄍㄜ", pinyin: "gē" },
  "弟": { zhuyin: "ㄉㄧˋ", pinyin: "dì" },
  "姐": { zhuyin: "ㄐㄧㄝˇ", pinyin: "jiě" },
  "妹": { zhuyin: "ㄇㄟˋ", pinyin: "mèi" },
  "爺": { zhuyin: "ㄧㄝˊ", pinyin: "yé" },
  "爷": { zhuyin: "ㄧㄝˊ", pinyin: "yé" },
  "奶": { zhuyin: "ㄋㄞˇ", pinyin: "nǎi" },
  "跑": { zhuyin: "ㄆㄠˇ", pinyin: "pǎo" },
  "跳": { zhuyin: "ㄊㄧㄠˋ", pinyin: "tiào" },
  "喝": { zhuyin: "ㄏㄜ", pinyin: "hē" },
  "玩": { zhuyin: "ㄨㄢˊ", pinyin: "wán" },
  "狗": { zhuyin: "ㄍㄡˇ", pinyin: "gǒu" },
  "貓": { zhuyin: "ㄇㄠ", pinyin: "māo" },
  "猫": { zhuyin: "ㄇㄠ", pinyin: "māo" },
  "果": { zhuyin: "ㄍㄨㄛˇ", pinyin: "guǒ" },
  "瓜": { zhuyin: "ㄍㄨㄚ", pinyin: "guā" },
  "豆": { zhuyin: "ㄉㄡˋ", pinyin: "dòu" },
  "米": { zhuyin: "ㄇㄧˇ", pinyin: "mǐ" },
  "飯": { zhuyin: "ㄈㄢˋ", pinyin: "fàn" },
  "饭": { zhuyin: "ㄈㄢˋ", pinyin: "fàn" },
  "車": { zhuyin: "ㄔㄜ", pinyin: "chē" },
  "车": { zhuyin: "ㄔㄜ", pinyin: "chē" }
};

/**
 * Returns phonetic string (Zhuyin or Pinyin) based on learning script mode.
 */
export function getCharPhonetic(
  char: string,
  scriptMode: "zhuyin" | "pinyin" | "dual" = "zhuyin"
): string | null {
  const item = PHONETIC_DICT[char];
  if (!item) return null;
  if (scriptMode === "pinyin") return item.pinyin;
  if (scriptMode === "zhuyin") return item.zhuyin;
  // In dual mode:
  return item.zhuyin || item.pinyin;
}

export interface RubyTextProps {
  text: string;
  isBeginner?: boolean;
  scriptMode?: "zhuyin" | "pinyin" | "dual";
  className?: string;
}

/**
 * Renders Chinese text with phonetic ruby annotations when Beginner Mode is enabled.
 */
export function RubyText({
  text,
  isBeginner = true,
  scriptMode = "zhuyin",
  className = ""
}: RubyTextProps): ReactNode {
  if (!isBeginner || !text) {
    return <span className={className}>{text}</span>;
  }

  const chars = Array.from(text);
  const elements: ReactNode[] = [];

  for (let i = 0; i < chars.length; i++) {
    const char = chars[i];
    // Check if Chinese character
    if (/[\u4e00-\u9fa5]/.test(char)) {
      const phonetic = getCharPhonetic(char, scriptMode);
      if (phonetic) {
        elements.push(
          <ruby key={i} className="ruby-annotated-char">
            <rt className="ruby-rt">{phonetic}</rt>
            <span className="ruby-base">{char}</span>
          </ruby>
        );
      } else {
        elements.push(
          <span key={i} className="ruby-char-plain">
            {char}
          </span>
        );
      }
    } else {
      // Non-Chinese characters, whitespace, digits, punctuation, or emoji
      // Wrap in matching ruby structure with invisible rt placeholder to guarantee 100% baseline synchronization
      elements.push(
        <ruby key={i} className="ruby-annotated-char ruby-punct-wrap">
          <rt className="ruby-rt ruby-rt-invisible" aria-hidden="true">&nbsp;</rt>
          <span className="ruby-base ruby-base-punct">{char}</span>
        </ruby>
      );
    }
  }

  return <span className={`ruby-text-container ${className}`}>{elements}</span>;
}

/**
 * Helper to render annotated text in JSX
 */
export function renderRuby(
  text: string,
  isBeginner: boolean,
  scriptMode: "zhuyin" | "pinyin" | "dual" = "zhuyin",
  className = ""
): ReactNode {
  return (
    <RubyText
      text={text}
      isBeginner={isBeginner}
      scriptMode={scriptMode}
      className={className}
    />
  );
}
